// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val arrayFunctions = mapOf(
    "append" to VRLFunction(
        name = "append",
        description = "Appends each item in the <code>items</code> array to the end of the <code>value</code> array.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The initial array.",
                true
            ),
            VRLFunctionArgument(
                "items",
                setOf("array"),
                "The items to append.",
                true
            )
        ),
        returnTypes = setOf("array")
    ),
    "chunks" to VRLFunction(
        name = "chunks",
        description = "Chunks <code>value</code> into slices of length <code>chunk_size</code> bytes.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The array of bytes to split.",
                true
            ),
            VRLFunctionArgument(
                "chunk_size",
                setOf("integer"),
                "The desired length of each chunk in bytes. This may be constrained by the host platform architecture.",
                true
            )
        ),
        returnTypes = setOf("array", "error")
    ),
    "pop" to VRLFunction(
        name = "pop",
        description = "Removes the last item from the <code>value</code> array.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The target array.",
                true
            )
        ),
        returnTypes = setOf("array")
    ),
    "push" to VRLFunction(
        name = "push",
        description = "Adds the <code>item</code> to the end of the <code>value</code> array.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The target array.",
                true
            ),
            VRLFunctionArgument(
                "item",
                setOf("any"),
                "The item to push.",
                true
            )
        ),
        returnTypes = setOf("array")
    ),
    "zip" to VRLFunction(
        name = "zip",
        description = "<p>Iterate over several arrays in parallel, producing a new array containing arrays of items from each source. The resulting array will be as long as the shortest input array, with all the remaining elements dropped. This function is modeled from the <code>zip</code> function <a href=\"https://docs.python.org/3/library/functions.html#zip\">in Python</a>, but similar methods can be found in <a href=\"https://docs.ruby-lang.org/en/master/Array.html#method-i-zip\">Ruby</a> and <a href=\"https://doc.rust-lang.org/stable/std/iter/trait.Iterator.html#method.zip\">Rust</a>.</p>\n\n<p>If a single parameter is given, it must contain an array of all the input arrays.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "array_0",
                setOf("array"),
                "The first array of elements, or the array of input arrays if no other parameter is present.",
                true
            ),
            VRLFunctionArgument(
                "array_1",
                setOf("array"),
                "The second array of elements. If not present, the first parameter contains all the arrays.",
                false
            )
        ),
        returnTypes = setOf("array", "error")
    )
)
