// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val checksumFunctions = mapOf(
    "crc" to VRLFunction(
        name = "crc",
        description = "<p>Calculates a CRC of the <code>value</code>.The CRC <code>algorithm</code> used can be optionally specified.</p>\n\n<p>This function is infallible if either the default <code>algorithm</code> value or a recognized-valid compile-time <code>algorithm</code> string literal is used. Otherwise, it is fallible.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the checksum for.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The CRC algorithm to use.",
                false,
                defaultValue = "CRC_32_ISO_HDLC"
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Create CRC checksum using the default algorithm",
                "crc(\"foo\")",
                "2356372769",
                false
            ),
            VRLFunctionExample(
                "Create CRC checksum using the CRC_32_CKSUM algorithm",
                "crc(\"foo\", algorithm: \"CRC_32_CKSUM\")",
                "4271552933",
                false
            )
        )
    ),
    "xxhash" to VRLFunction(
        name = "xxhash",
        description = "Calculates a <a href=\"https://github.com/DoumanAsh/xxhash-rust\">xxHash</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The xxHash hashing algorithm to use.",
                false,
                defaultValue = "XXH32"
            )
        ),
        returnTypes = setOf("string", "integer"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate a hash using the default (XXH32) algorithm",
                "xxhash(\"foo\")",
                "3792637401",
                false
            ),
            VRLFunctionExample(
                "Calculate a hash using the XXH32 algorithm",
                "xxhash(\"foo\", \"XXH32\")",
                "3792637401",
                false
            ),
            VRLFunctionExample(
                "Calculate a hash using the XXH64 algorithm",
                "xxhash(\"foo\", \"XXH64\")",
                "3728699739546630700",
                false
            ),
            VRLFunctionExample(
                "Calculate a hash using the XXH3-64 algorithm",
                "xxhash(\"foo\", \"XXH3-64\")",
                "-6093828362558604000",
                false
            ),
            VRLFunctionExample(
                "Calculate a hash using the XXH3-128 algorithm",
                "xxhash(\"foo\", \"XXH3-128\")",
                "161745101148472925293886522910304009610",
                false
            )
        )
    )
)
