// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val checksumFunctions = mapOf(
    "crc" to VRLFunction(
        name = "crc",
        description = "<p>Calculates a CRC of the <code>value</code>.The CRC <code>algorithm</code> used can be optionally specified.</p>\n\n<p>This function is infallible if either the default <code>algorithm</code> value or a recognized-valid compile-time <code>algorithm</code> string literal is used. Otherwise, it is fallible.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the checksum for.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The CRC algorithm to use.",
                false,
                defaultValue = "CRC_32_ISO_HDLC"
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "xxhash" to VRLFunction(
        name = "xxhash",
        description = "Calculates a <a href=\"https://github.com/DoumanAsh/xxhash-rust\">xxHash</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The xxHash hashing algorithm to use.",
                false,
                defaultValue = "XXH32"
            )
        ),
        returnTypes = setOf("string", "integer")
    )
)
