// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val codecFunctions = mapOf(
    "decode_base16" to VRLFunction(
        name = "decode_base16",
        description = "Decodes the <code>value</code> (a <a href=\"https://en.wikipedia.org/wiki/Hexadecimal\">Base16</a> string) into its original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The <a href=\"https://en.wikipedia.org/wiki/Hexadecimal\">Base16</a> data to decode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_base64" to VRLFunction(
        name = "decode_base64",
        description = "Decodes the <code>value</code> (a <a href=\"https://en.wikipedia.org/wiki/Base64\">Base64</a> string) into its original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The <a href=\"https://en.wikipedia.org/wiki/Base64\">Base64</a> data to decode.",
                true
            ),
            VRLFunctionArgument(
                "charset",
                setOf("string"),
                "The character set to use when decoding the data.",
                false,
                defaultValue = "standard"
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_charset" to VRLFunction(
        name = "decode_charset",
        description = "Decodes the <code>value</code> (a non-UTF8 string) to a UTF8 string using the specified <a href=\"https://encoding.spec.whatwg.org/#names-and-labels\">character set</a>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The non-UTF8 string to decode.",
                true
            ),
            VRLFunctionArgument(
                "from_charset",
                setOf("string"),
                "The <a href=\"https://encoding.spec.whatwg.org/#names-and-labels\">character set</a> to use when decoding the data.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_gzip" to VRLFunction(
        name = "decode_gzip",
        description = "Decodes the <code>value</code> (a <a href=\"https://www.gzip.org/\">Gzip</a> string) into its original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The <a href=\"https://www.gzip.org/\">Gzip</a> data to decode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_lz4" to VRLFunction(
        name = "decode_lz4",
        description = "Decodes the <code>value</code> (an lz4 string) into its original string. <code>buf_size</code> is the size of the buffer to decode into, this must be equal to or larger than the uncompressed size. If <code>prepended_size</code> is set to <code>true</code>, it expects the original uncompressed size to be prepended to the compressed data. <code>prepended_size</code> is useful for some implementations of lz4 that require the original size to be known before decoding.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The lz4 block data to decode.",
                true
            ),
            VRLFunctionArgument(
                "buf_size",
                setOf("integer"),
                "The size of the buffer to decode into, this must be equal to or larger than the uncompressed size.",
                false,
                defaultValue = 1000000
            ),
            VRLFunctionArgument(
                "prepended_size",
                setOf("boolean"),
                "Some implementations of lz4 require the original uncompressed size to be prepended to the compressed data.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_mime_q" to VRLFunction(
        name = "decode_mime_q",
        description = "Replaces q-encoded or base64-encoded <a href=\"https://datatracker.ietf.org/doc/html/rfc2047#section-2\">encoded-word</a> substrings in the <code>value</code> with their original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string with <a href=\"https://datatracker.ietf.org/doc/html/rfc2047#section-2\">encoded-words</a> to decode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_percent" to VRLFunction(
        name = "decode_percent",
        description = "Decodes a <a href=\"https://url.spec.whatwg.org/#percent-encoded-bytes\">percent-encoded</a> <code>value</code> like a URL.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to decode.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "decode_punycode" to VRLFunction(
        name = "decode_punycode",
        description = "Decodes a <a href=\"https://en.wikipedia.org/wiki/Punycode\">punycode</a> encoded <code>value</code>, such as an internationalized domain name (<a href=\"https://en.wikipedia.org/wiki/Internationalized_domain_name\">IDN</a>). This function assumes that the value passed is meant to be used in IDN context and that it is either a domain name or a part of it.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to decode.",
                true
            ),
            VRLFunctionArgument(
                "validate",
                setOf("boolean"),
                "If enabled, checks if the input string is a valid domain name.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_snappy" to VRLFunction(
        name = "decode_snappy",
        description = "Decodes the <code>value</code> (a Snappy string) into its original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The Snappy data to decode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_zlib" to VRLFunction(
        name = "decode_zlib",
        description = "Decodes the <code>value</code> (a <a href=\"https://www.zlib.net\">Zlib</a> string) into its original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The <a href=\"https://www.zlib.net\">Zlib</a> data to decode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "decode_zstd" to VRLFunction(
        name = "decode_zstd",
        description = "Decodes the <code>value</code> (a <a href=\"https://facebook.github.io/zstd\">Zstandard</a> string) into its original string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The <a href=\"https://facebook.github.io/zstd\">Zstandard</a> data to decode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_base16" to VRLFunction(
        name = "encode_base16",
        description = "Encodes the <code>value</code> to <a href=\"https://en.wikipedia.org/wiki/Hexadecimal\">Base16</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_base64" to VRLFunction(
        name = "encode_base64",
        description = "Encodes the <code>value</code> to <a href=\"https://en.wikipedia.org/wiki/Base64\">Base64</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "padding",
                setOf("boolean"),
                "Whether the Base64 output is <a href=\"https://en.wikipedia.org/wiki/Base64#Output_padding\">padded</a>.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "charset",
                setOf("string"),
                "The character set to use when encoding the data.",
                false,
                defaultValue = "standard"
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_charset" to VRLFunction(
        name = "encode_charset",
        description = "Encodes the <code>value</code> (a UTF8 string) to a non-UTF8 string using the specified <a href=\"https://encoding.spec.whatwg.org/#names-and-labels\">character set</a>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The UTF8 string to encode.",
                true
            ),
            VRLFunctionArgument(
                "to_charset",
                setOf("string"),
                "The <a href=\"https://encoding.spec.whatwg.org/#names-and-labels\">character set</a> to use when encoding the data.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_csv" to VRLFunction(
        name = "encode_csv",
        description = "Encodes the <code>value</code> to a single CSV formatted row.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to convert to a CSV string.",
                true
            ),
            VRLFunctionArgument(
                "delimiter",
                setOf("string"),
                "The field delimiter to use when encoding. Must be a single-byte UTF-8 character.",
                false,
                defaultValue = ","
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_gzip" to VRLFunction(
        name = "encode_gzip",
        description = "Encodes the <code>value</code> to <a href=\"https://www.gzip.org/\">Gzip</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "compression_level",
                setOf("integer"),
                "The default compression level.",
                false,
                defaultValue = 6
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_json" to VRLFunction(
        name = "encode_json",
        description = "Encodes the <code>value</code> to JSON.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to convert to a JSON string.",
                true
            ),
            VRLFunctionArgument(
                "pretty",
                setOf("boolean"),
                "Whether to pretty print the JSON string or not.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_key_value" to VRLFunction(
        name = "encode_key_value",
        description = "Encodes the <code>value</code> into key-value format with customizable delimiters. Default delimiters match the <a href=\"https://brandur.org/logfmt\">logfmt</a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The value to convert to a string.",
                true
            ),
            VRLFunctionArgument(
                "fields_ordering",
                setOf("array"),
                "The ordering of fields to preserve. Any fields not in this list are listed unordered, after all ordered fields.",
                false,
                defaultValue = "[]"
            ),
            VRLFunctionArgument(
                "key_value_delimiter",
                setOf("string"),
                "The string that separates the key from the value.",
                false,
                defaultValue = "="
            ),
            VRLFunctionArgument(
                "field_delimiter",
                setOf("string"),
                "The string that separates each key-value pair.",
                false,
                defaultValue = ""
            ),
            VRLFunctionArgument(
                "flatten_boolean",
                setOf("boolean"),
                "Whether to encode key-value with a boolean value as a standalone key if <code>true</code> and nothing if <code>false</code>.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_logfmt" to VRLFunction(
        name = "encode_logfmt",
        description = "Encodes the <code>value</code> to <a href=\"https://brandur.org/logfmt\">logfmt</a>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The value to convert to a logfmt string.",
                true
            ),
            VRLFunctionArgument(
                "fields_ordering",
                setOf("array"),
                "The ordering of fields to preserve. Any fields not in this list are listed unordered, after all ordered fields.",
                false,
                defaultValue = "[]"
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_lz4" to VRLFunction(
        name = "encode_lz4",
        description = "Encodes the <code>value</code> to <a href=\"https://lz4.github.io/lz4/\">Lz4</a>. This function compresses the input string into an lz4 block. If <code>prepend_size</code> is set to <code>true</code>, it prepends the original uncompressed size to the compressed data. This is useful for some implementations of lz4 that require the original size to be known before decoding.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "prepend_size",
                setOf("boolean"),
                "Whether to prepend the original size to the compressed data.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_percent" to VRLFunction(
        name = "encode_percent",
        description = "Encodes a <code>value</code> with <a href=\"https://url.spec.whatwg.org/#percent-encoded-bytes\">percent encoding</a> to safely be used in URLs.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "ascii_set",
                setOf("string"),
                "The ASCII set to use when encoding the data.",
                false,
                defaultValue = "NON_ALPHANUMERIC"
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_proto" to VRLFunction(
        name = "encode_proto",
        description = "Encodes the <code>value</code> into a protocol buffer payload.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The object to convert to a protocol buffer payload.",
                true
            ),
            VRLFunctionArgument(
                "desc_file",
                setOf("string"),
                "<p>The path to the protobuf descriptor set file. Must be a literal string.</p><p>This file is the output of protoc -o …</p>",
                true
            ),
            VRLFunctionArgument(
                "message_type",
                setOf("string"),
                "<p>The name of the message type to use for serializing.</p><p>Must be a literal string.</p>",
                true
            ),
            VRLFunctionArgument(
                "allow_lossy_string_coercion",
                setOf("boolean"),
                "Whether to permit lossy coercion of <code>Boolean</code>, <code>Integer</code>, <code>Float</code>, and <code>Timestamp</code> values into protobuf <code>string</code> fields by stringifying the value. Defaults to <code>true</code> to preserve permissive behavior; set to <code>false</code> for strict, spec-compliant encoding (see the <a href=\"https://protobuf.dev/programming-guides/json/\">protobuf JSON mapping</a>).",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_punycode" to VRLFunction(
        name = "encode_punycode",
        description = "Encodes a <code>value</code> to <a href=\"https://en.wikipedia.org/wiki/Punycode\">punycode</a>. Useful for internationalized domain names (<a href=\"https://en.wikipedia.org/wiki/Internationalized_domain_name\">IDN</a>). This function assumes that the value passed is meant to be used in IDN context and that it is either a domain name or a part of it.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "validate",
                setOf("boolean"),
                "Whether to validate the input string to check if it is a valid domain name.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_snappy" to VRLFunction(
        name = "encode_snappy",
        description = "Encodes the <code>value</code> to Snappy.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encode_zlib" to VRLFunction(
        name = "encode_zlib",
        description = "Encodes the <code>value</code> to <a href=\"https://www.zlib.net\">Zlib</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "compression_level",
                setOf("integer"),
                "The default compression level.",
                false,
                defaultValue = 6
            )
        ),
        returnTypes = setOf("string")
    ),
    "encode_zstd" to VRLFunction(
        name = "encode_zstd",
        description = "Encodes the <code>value</code> to <a href=\"https://facebook.github.io/zstd\">Zstandard</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to encode.",
                true
            ),
            VRLFunctionArgument(
                "compression_level",
                setOf("integer"),
                "The default compression level.",
                false,
                defaultValue = 3
            )
        ),
        returnTypes = setOf("string")
    )
)
