// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val convertFunctions = mapOf(
    "from_unix_timestamp" to VRLFunction(
        name = "from_unix_timestamp",
        description = "<p>Converts the <code>value</code> integer from a <a href=\"https://en.wikipedia.org/wiki/Unix_time\">Unix timestamp</a> to a VRL <code>timestamp</code>.</p>\n\n<p>Converts from the number of seconds since the Unix epoch by default. To convert from milliseconds or nanoseconds, set the <code>unit</code> argument to <code>milliseconds</code> or <code>nanoseconds</code>.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The Unix timestamp to convert.",
                true
            ),
            VRLFunctionArgument(
                "unit",
                setOf("string"),
                "The time unit.",
                false,
                defaultValue = "seconds"
            )
        ),
        returnTypes = setOf("timestamp"),
        examples = listOf(
            VRLFunctionExample(
                "Convert from a Unix timestamp (seconds)",
                "from_unix_timestamp!(5)",
                "t'1970-01-01T00:00:05Z'",
                false
            ),
            VRLFunctionExample(
                "Convert from a Unix timestamp (milliseconds)",
                "from_unix_timestamp!(5000, unit: \"milliseconds\")",
                "t'1970-01-01T00:00:05Z'",
                false
            ),
            VRLFunctionExample(
                "Convert from a Unix timestamp (microseconds)",
                "from_unix_timestamp!(5000, unit: \"microseconds\")",
                "t'1970-01-01T00:00:00.005Z'",
                false
            ),
            VRLFunctionExample(
                "Convert from a Unix timestamp (nanoseconds)",
                "from_unix_timestamp!(5000, unit: \"nanoseconds\")",
                "t'1970-01-01T00:00:00.000005Z'",
                false
            )
        )
    ),
    "to_syslog_facility" to VRLFunction(
        name = "to_syslog_facility",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Facility\">facility code</a>, into its corresponding Syslog keyword. For example, <code>0</code> into <code>\"kern\"</code>, <code>1</code> into <code>\"user\"</code>, etc.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The facility code.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Coerce to a Syslog facility",
                "to_syslog_facility!(4)",
                "auth",
                false
            ),
            VRLFunctionExample(
                "invalid",
                "to_syslog_facility!(500)",
                "function call error for \"to_syslog_facility\" at (0:24): facility code 500 not valid",
                true
            )
        )
    ),
    "to_syslog_facility_code" to VRLFunction(
        name = "to_syslog_facility_code",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Facility\">facility keyword</a>, into a Syslog integer facility code (<code>0</code> to <code>23</code>).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The Syslog facility keyword to convert.",
                true
            )
        ),
        returnTypes = setOf("integer", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Coerce to Syslog facility code",
                "to_syslog_facility_code!(\"authpriv\")",
                "10",
                false
            ),
            VRLFunctionExample(
                "invalid",
                "to_syslog_facility_code!(s'foobar')",
                "function call error for \"to_syslog_facility_code\" at (0:35): syslog facility 'foobar' not valid",
                true
            )
        )
    ),
    "to_syslog_level" to VRLFunction(
        name = "to_syslog_level",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Severity_level\">severity level</a>, into its corresponding keyword, i.e. 0 into <code>\"emerg\"</code>, 1 into <code>\"alert\"</code>, etc.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The severity level.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Coerce to a Syslog level",
                "to_syslog_level!(5)",
                "notice",
                false
            ),
            VRLFunctionExample(
                "invalid",
                "to_syslog_level!(500)",
                "function call error for \"to_syslog_level\" at (0:21): severity level 500 not valid",
                true
            )
        )
    ),
    "to_syslog_severity" to VRLFunction(
        name = "to_syslog_severity",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Severity_level\">log level keyword</a>, into a Syslog integer severity level (<code>0</code> to <code>7</code>).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The Syslog level keyword to convert.",
                true
            )
        ),
        returnTypes = setOf("integer", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Coerce to Syslog severity",
                "to_syslog_severity!(\"alert\")",
                "1",
                false
            ),
            VRLFunctionExample(
                "invalid",
                "to_syslog_severity!(s'foobar')",
                "function call error for \"to_syslog_severity\" at (0:30): syslog level foobar not valid",
                true
            )
        )
    ),
    "to_unix_timestamp" to VRLFunction(
        name = "to_unix_timestamp",
        description = "<p>Converts the <code>value</code> timestamp into a <a href=\"https://en.wikipedia.org/wiki/Unix_time\">Unix timestamp</a>.</p>\n\n<p>Returns the number of seconds since the Unix epoch by default. To return the number in milliseconds or nanoseconds, set the <code>unit</code> argument to <code>milliseconds</code> or <code>nanoseconds</code>.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("timestamp"),
                "The timestamp to convert into a Unix timestamp.",
                true
            ),
            VRLFunctionArgument(
                "unit",
                setOf("string"),
                "The time unit.",
                false,
                defaultValue = "seconds"
            )
        ),
        returnTypes = setOf("integer", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Convert to a Unix timestamp (seconds)",
                "to_unix_timestamp(t'2021-01-01T00:00:00+00:00')",
                "1609459200",
                false
            ),
            VRLFunctionExample(
                "Convert to a Unix timestamp (milliseconds)",
                "to_unix_timestamp(t'2021-01-01T00:00:00Z', unit: \"milliseconds\")",
                "1609459200000",
                false
            ),
            VRLFunctionExample(
                "Convert to a Unix timestamp (microseconds)",
                "to_unix_timestamp(t'2021-01-01T00:00:00Z', unit: \"microseconds\")",
                "1609459200000000",
                false
            ),
            VRLFunctionExample(
                "Convert to a Unix timestamp (nanoseconds)",
                "to_unix_timestamp(t'2021-01-01T00:00:00Z', unit: \"nanoseconds\")",
                "1609459200000000000",
                false
            )
        )
    )
)
