// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val convertFunctions = mapOf(
    "from_unix_timestamp" to VRLFunction(
        name = "from_unix_timestamp",
        description = "<p>Converts the <code>value</code> integer from a <a href=\"https://en.wikipedia.org/wiki/Unix_time\">Unix timestamp</a> to a VRL <code>timestamp</code>.</p>\n\n<p>Converts from the number of seconds since the Unix epoch by default. To convert from milliseconds or nanoseconds, set the <code>unit</code> argument to <code>milliseconds</code> or <code>nanoseconds</code>.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The Unix timestamp to convert.",
                true
            ),
            VRLFunctionArgument(
                "unit",
                setOf("string"),
                "The time unit.",
                false,
                defaultValue = "seconds"
            )
        ),
        returnTypes = setOf("timestamp")
    ),
    "to_syslog_facility" to VRLFunction(
        name = "to_syslog_facility",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Facility\">facility code</a>, into its corresponding Syslog keyword. For example, <code>0</code> into <code>\"kern\"</code>, <code>1</code> into <code>\"user\"</code>, etc.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The facility code.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "to_syslog_facility_code" to VRLFunction(
        name = "to_syslog_facility_code",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Facility\">facility keyword</a>, into a Syslog integer facility code (<code>0</code> to <code>23</code>).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The Syslog facility keyword to convert.",
                true
            )
        ),
        returnTypes = setOf("integer", "error")
    ),
    "to_syslog_level" to VRLFunction(
        name = "to_syslog_level",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Severity_level\">severity level</a>, into its corresponding keyword, i.e. 0 into <code>\"emerg\"</code>, 1 into <code>\"alert\"</code>, etc.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The severity level.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "to_syslog_severity" to VRLFunction(
        name = "to_syslog_severity",
        description = "Converts the <code>value</code>, a Syslog <a href=\"https://en.wikipedia.org/wiki/Syslog#Severity_level\">log level keyword</a>, into a Syslog integer severity level (<code>0</code> to <code>7</code>).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The Syslog level keyword to convert.",
                true
            )
        ),
        returnTypes = setOf("integer", "error")
    ),
    "to_unix_timestamp" to VRLFunction(
        name = "to_unix_timestamp",
        description = "<p>Converts the <code>value</code> timestamp into a <a href=\"https://en.wikipedia.org/wiki/Unix_time\">Unix timestamp</a>.</p>\n\n<p>Returns the number of seconds since the Unix epoch by default. To return the number in milliseconds or nanoseconds, set the <code>unit</code> argument to <code>milliseconds</code> or <code>nanoseconds</code>.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("timestamp"),
                "The timestamp to convert into a Unix timestamp.",
                true
            ),
            VRLFunctionArgument(
                "unit",
                setOf("string"),
                "The time unit.",
                false,
                defaultValue = "seconds"
            )
        ),
        returnTypes = setOf("integer", "error")
    )
)
