// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val cryptographyFunctions = mapOf(
    "decrypt" to VRLFunction(
        name = "decrypt",
        description = "<p>Decrypts a string with a symmetric encryption algorithm.</p>\n\n<p>Supported Algorithms:</p><ul><li>AES-256-CFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-OFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-OFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-OFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-128-SIV (key = 32 bytes, iv = 16 bytes)</li><li>AES-256-SIV (key = 64 bytes, iv = 16 bytes)</li><li>Deprecated - AES-256-CTR (key = 32 bytes, iv = 16 bytes)</li><li>Deprecated - AES-192-CTR (key = 24 bytes, iv = 16 bytes)</li><li>Deprecated - AES-128-CTR (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-LE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-LE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-LE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-BE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-BE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-BE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-PKCS7 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-PKCS7 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-PKCS7 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ANSIX923 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ANSIX923 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ANSIX923 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO7816 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO7816 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO7816 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO10126 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO10126 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO10126 (key = 16 bytes, iv = 16 bytes)</li><li>CHACHA20-POLY1305 (key = 32 bytes, iv = 12 bytes)</li><li>XCHACHA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li><li>XSALSA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "ciphertext",
                setOf("string"),
                "The string in raw bytes (not encoded) to decrypt.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The algorithm to use.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The key in raw bytes (not encoded) for decryption. The length must match the algorithm requested.",
                true
            ),
            VRLFunctionArgument(
                "iv",
                setOf("string"),
                "The IV in raw bytes (not encoded) for decryption. The length must match the algorithm requested. A new IV should be generated for every message. You can use <code>random_bytes</code> to generate a cryptographically secure random value. The value should match the one used during encryption.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "encrypt" to VRLFunction(
        name = "encrypt",
        description = "<p>Encrypts a string with a symmetric encryption algorithm.</p>\n\n<p>Supported Algorithms:</p><ul><li>AES-256-CFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-OFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-OFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-OFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-128-SIV (key = 32 bytes, iv = 16 bytes)</li><li>AES-256-SIV (key = 64 bytes, iv = 16 bytes)</li><li>Deprecated - AES-256-CTR (key = 32 bytes, iv = 16 bytes)</li><li>Deprecated - AES-192-CTR (key = 24 bytes, iv = 16 bytes)</li><li>Deprecated - AES-128-CTR (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-LE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-LE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-LE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-BE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-BE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-BE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-PKCS7 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-PKCS7 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-PKCS7 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ANSIX923 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ANSIX923 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ANSIX923 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO7816 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO7816 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO7816 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO10126 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO10126 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO10126 (key = 16 bytes, iv = 16 bytes)</li><li>CHACHA20-POLY1305 (key = 32 bytes, iv = 12 bytes)</li><li>XCHACHA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li><li>XSALSA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "plaintext",
                setOf("string"),
                "The string to encrypt.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The algorithm to use.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The key in raw bytes (not encoded) for encryption. The length must match the algorithm requested.",
                true
            ),
            VRLFunctionArgument(
                "iv",
                setOf("string"),
                "The IV in raw bytes (not encoded) for encryption. The length must match the algorithm requested. A new IV should be generated for every message. You can use <code>random_bytes</code> to generate a cryptographically secure random value.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "hmac" to VRLFunction(
        name = "hmac",
        description = "<p>Calculates a <a href=\"https://en.wikipedia.org/wiki/HMAC\">HMAC</a> of the <code>value</code> using the given <code>key</code>. The hashing <code>algorithm</code> used can be optionally specified.</p>\n\n<p>For most use cases, the resulting bytestream should be encoded into a hex or base64 string using either <a href=\"https://vector.dev/docs/reference/vrl/functions/#encode_base16\">encode_base16</a> or <a href=\"https://vector.dev/docs/reference/vrl/functions/#encode_base64\">encode_base64</a>.</p>\n\n<p>This function is infallible if either the default <code>algorithm</code> value or a recognized-valid compile-time <code>algorithm</code> string literal is used. Otherwise, it is fallible.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the HMAC for.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The string to use as the cryptographic key.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The hashing algorithm to use.",
                false,
                defaultValue = "SHA-256",
                enumValues = listOf("SHA1", "SHA-224", "SHA-256", "SHA-384", "SHA-512")
            )
        ),
        returnTypes = setOf("string")
    ),
    "md5" to VRLFunction(
        name = "md5",
        description = "Calculates an md5 hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "seahash" to VRLFunction(
        name = "seahash",
        description = "Calculates a <a href=\"https://docs.rs/seahash/latest/seahash/\">Seahash</a> hash of the <code>value</code>. <strong>Note</strong>: Due to limitations in the underlying VRL data types, this function converts the unsigned 64-bit integer SeaHash result to a signed 64-bit integer. Results higher than the signed 64-bit integer maximum value wrap around to negative values.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            )
        ),
        returnTypes = setOf("integer")
    ),
    "sha1" to VRLFunction(
        name = "sha1",
        description = "Calculates a <a href=\"https://en.wikipedia.org/wiki/SHA-1\">SHA-1</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "sha2" to VRLFunction(
        name = "sha2",
        description = "Calculates a <a href=\"https://en.wikipedia.org/wiki/SHA-2\">SHA-2</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The variant of the algorithm to use.",
                false,
                defaultValue = "SHA-512/256",
                enumValues = listOf("SHA-224", "SHA-256", "SHA-384", "SHA-512", "SHA-512/224", "SHA-512/256")
            )
        ),
        returnTypes = setOf("string")
    ),
    "sha3" to VRLFunction(
        name = "sha3",
        description = "Calculates a <a href=\"https://en.wikipedia.org/wiki/SHA-3\">SHA-3</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The variant of the algorithm to use.",
                false,
                defaultValue = "SHA3-512",
                enumValues = listOf("SHA3-224", "SHA3-256", "SHA3-384", "SHA3-512")
            )
        ),
        returnTypes = setOf("string")
    )
)
