// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val cryptographyFunctions = mapOf(
    "decrypt" to VRLFunction(
        name = "decrypt",
        description = "<p>Decrypts a string with a symmetric encryption algorithm.</p>\n\n<p>Supported Algorithms:</p><ul><li>AES-256-CFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-OFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-OFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-OFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-128-SIV (key = 32 bytes, iv = 16 bytes)</li><li>AES-256-SIV (key = 64 bytes, iv = 16 bytes)</li><li>Deprecated - AES-256-CTR (key = 32 bytes, iv = 16 bytes)</li><li>Deprecated - AES-192-CTR (key = 24 bytes, iv = 16 bytes)</li><li>Deprecated - AES-128-CTR (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-LE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-LE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-LE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-BE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-BE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-BE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-PKCS7 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-PKCS7 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-PKCS7 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ANSIX923 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ANSIX923 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ANSIX923 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO7816 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO7816 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO7816 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO10126 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO10126 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO10126 (key = 16 bytes, iv = 16 bytes)</li><li>CHACHA20-POLY1305 (key = 32 bytes, iv = 12 bytes)</li><li>XCHACHA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li><li>XSALSA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "ciphertext",
                setOf("string"),
                "The string in raw bytes (not encoded) to decrypt.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The algorithm to use.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The key in raw bytes (not encoded) for decryption. The length must match the algorithm requested.",
                true
            ),
            VRLFunctionArgument(
                "iv",
                setOf("string"),
                "The IV in raw bytes (not encoded) for decryption. The length must match the algorithm requested. A new IV should be generated for every message. You can use <code>random_bytes</code> to generate a cryptographically secure random value. The value should match the one used during encryption.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Decrypt value using AES-256-CFB",
                "iv = \"0123456789012345\"\nkey = \"01234567890123456789012345678912\"\nciphertext = decode_base64!(\"c/dIOA==\")\ndecrypt!(ciphertext, \"AES-256-CFB\", key: key, iv: iv)",
                "data",
                false
            ),
            VRLFunctionExample(
                "Decrypt value using AES-128-CBC-PKCS7",
                "iv = decode_base64!(\"fVEIRkIiczCRWNxaarsyxA==\")\nkey = \"16_byte_keyxxxxx\"\nciphertext = decode_base64!(\"5fLGcu1VHdzsPcGNDio7asLqE1P43QrVfPfmP4i4zOU=\")\ndecrypt!(ciphertext, \"AES-128-CBC-PKCS7\", key: key, iv: iv)",
                "super_secret_message",
                false
            )
        )
    ),
    "encrypt" to VRLFunction(
        name = "encrypt",
        description = "<p>Encrypts a string with a symmetric encryption algorithm.</p>\n\n<p>Supported Algorithms:</p><ul><li>AES-256-CFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-OFB (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-OFB (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-OFB (key = 16 bytes, iv = 16 bytes)</li><li>AES-128-SIV (key = 32 bytes, iv = 16 bytes)</li><li>AES-256-SIV (key = 64 bytes, iv = 16 bytes)</li><li>Deprecated - AES-256-CTR (key = 32 bytes, iv = 16 bytes)</li><li>Deprecated - AES-192-CTR (key = 24 bytes, iv = 16 bytes)</li><li>Deprecated - AES-128-CTR (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-LE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-LE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-LE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CTR-BE (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CTR-BE (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CTR-BE (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-PKCS7 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-PKCS7 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-PKCS7 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ANSIX923 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ANSIX923 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ANSIX923 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO7816 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO7816 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO7816 (key = 16 bytes, iv = 16 bytes)</li><li>AES-256-CBC-ISO10126 (key = 32 bytes, iv = 16 bytes)</li><li>AES-192-CBC-ISO10126 (key = 24 bytes, iv = 16 bytes)</li><li>AES-128-CBC-ISO10126 (key = 16 bytes, iv = 16 bytes)</li><li>CHACHA20-POLY1305 (key = 32 bytes, iv = 12 bytes)</li><li>XCHACHA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li><li>XSALSA20-POLY1305 (key = 32 bytes, iv = 24 bytes)</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "plaintext",
                setOf("string"),
                "The string to encrypt.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The algorithm to use.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The key in raw bytes (not encoded) for encryption. The length must match the algorithm requested.",
                true
            ),
            VRLFunctionArgument(
                "iv",
                setOf("string"),
                "The IV in raw bytes (not encoded) for encryption. The length must match the algorithm requested. A new IV should be generated for every message. You can use <code>random_bytes</code> to generate a cryptographically secure random value.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Encrypt value using AES-256-CFB",
                "iv = \"0123456789012345\" # typically you would call random_bytes(16)\nkey = \"01234567890123456789012345678912\"\nencrypted_message = encrypt!(\"data\", \"AES-256-CFB\", key: key, iv: iv)\nencode_base64(encrypted_message)",
                "c/dIOA==",
                false
            ),
            VRLFunctionExample(
                "Encrypt value using AES-128-CBC-PKCS7",
                "iv = \"1234567890123456\" # typically you would call random_bytes(16)\nkey = \"16_byte_keyxxxxx\"\nencrypted_message = encrypt!(\"super secret message\", \"AES-128-CBC-PKCS7\", key: key, iv: iv)\nencode_base64(encrypted_message)",
                "GBw8Mu00v0Kc38+/PvsVtGgWuUJ+ZNLgF8Opy8ohIYE=",
                false
            )
        )
    ),
    "hmac" to VRLFunction(
        name = "hmac",
        description = "<p>Calculates a <a href=\"https://en.wikipedia.org/wiki/HMAC\">HMAC</a> of the <code>value</code> using the given <code>key</code>. The hashing <code>algorithm</code> used can be optionally specified.</p>\n\n<p>For most use cases, the resulting bytestream should be encoded into a hex or base64 string using either <a href=\"https://vector.dev/docs/reference/vrl/functions/#encode_base16\">encode_base16</a> or <a href=\"https://vector.dev/docs/reference/vrl/functions/#encode_base64\">encode_base64</a>.</p>\n\n<p>This function is infallible if either the default <code>algorithm</code> value or a recognized-valid compile-time <code>algorithm</code> string literal is used. Otherwise, it is fallible.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the HMAC for.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The string to use as the cryptographic key.",
                true
            ),
            VRLFunctionArgument(
                "algorithm",
                setOf("string"),
                "The hashing algorithm to use.",
                false,
                defaultValue = "SHA-256",
                enumValues = listOf("SHA1", "SHA-224", "SHA-256", "SHA-384", "SHA-512")
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate message HMAC (defaults: SHA-256), encoding to a base64 string",
                "encode_base64(hmac(\"Hello there\", \"super-secret-key\"))",
                "eLGE8YMviv85NPXgISRUZxstBNSU47JQdcXkUWcClmI=",
                false
            ),
            VRLFunctionExample(
                "Calculate message HMAC using SHA-224, encoding to a hex-encoded string",
                "encode_base16(hmac(\"Hello there\", \"super-secret-key\", algorithm: \"SHA-224\"))",
                "42fccbc2b7d22a143b92f265a8046187558a94d11ddbb30622207e90",
                false
            ),
            VRLFunctionExample(
                "Calculate message HMAC using SHA1, encoding to a base64 string",
                "encode_base64(hmac(\"Hello there\", \"super-secret-key\", algorithm: \"SHA1\"))",
                "MiyBIHO8Set9+6crALiwkS0yFPE=",
                false
            ),
            VRLFunctionExample(
                "Calculate message HMAC using a variable hash algorithm",
                ".hash_algo = \"SHA-256\"\nhmac_bytes, err = hmac(\"Hello there\", \"super-secret-key\", algorithm: .hash_algo)\nif err == null {\n    .hmac = encode_base16(hmac_bytes)\n}",
                "78b184f1832f8aff3934f5e0212454671b2d04d494e3b25075c5e45167029662",
                false
            )
        )
    ),
    "md5" to VRLFunction(
        name = "md5",
        description = "Calculates an md5 hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Create md5 hash",
                "md5(\"foo\")",
                "acbd18db4cc2f85cedef654fccc4a4d8",
                false
            )
        )
    ),
    "seahash" to VRLFunction(
        name = "seahash",
        description = "Calculates a <a href=\"https://docs.rs/seahash/latest/seahash/\">Seahash</a> hash of the <code>value</code>. <strong>Note</strong>: Due to limitations in the underlying VRL data types, this function converts the unsigned 64-bit integer SeaHash result to a signed 64-bit integer. Results higher than the signed 64-bit integer maximum value wrap around to negative values.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            )
        ),
        returnTypes = setOf("integer"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate seahash",
                "seahash(\"foobar\")",
                "5348458858952426000",
                false
            ),
            VRLFunctionExample(
                "Calculate negative seahash",
                "seahash(\"bar\")",
                "-2796170501982571500",
                false
            )
        )
    ),
    "sha1" to VRLFunction(
        name = "sha1",
        description = "Calculates a <a href=\"https://en.wikipedia.org/wiki/SHA-1\">SHA-1</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate sha1 hash",
                "sha1(\"foo\")",
                "0beec7b5ea3f0fdbc95d0dd47f3c5bc275da8a33",
                false
            )
        )
    ),
    "sha2" to VRLFunction(
        name = "sha2",
        description = "Calculates a <a href=\"https://en.wikipedia.org/wiki/SHA-2\">SHA-2</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The variant of the algorithm to use.",
                false,
                defaultValue = "SHA-512/256",
                enumValues = listOf("SHA-224", "SHA-256", "SHA-384", "SHA-512", "SHA-512/224", "SHA-512/256")
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate sha2 hash using default variant",
                "sha2(\"foobar\")",
                "d014c752bc2be868e16330f47e0c316a5967bcbc9c286a457761d7055b9214ce",
                false
            ),
            VRLFunctionExample(
                "Calculate sha2 hash with SHA-512/224",
                "sha2(\"foo\", variant: \"SHA-512/224\")",
                "d68f258d37d670cfc1ec1001a0394784233f88f056994f9a7e5e99be",
                false
            ),
            VRLFunctionExample(
                "Calculate sha2 hash with SHA-384",
                "sha2(\"foobar\", \"SHA-384\")",
                "3c9c30d9f665e74d515c842960d4a451c83a0125fd3de7392d7b37231af10c72ea58aedfcdf89a5765bf902af93ecf06",
                false
            )
        )
    ),
    "sha3" to VRLFunction(
        name = "sha3",
        description = "Calculates a <a href=\"https://en.wikipedia.org/wiki/SHA-3\">SHA-3</a> hash of the <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to calculate the hash for.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The variant of the algorithm to use.",
                false,
                defaultValue = "SHA3-512",
                enumValues = listOf("SHA3-224", "SHA3-256", "SHA3-384", "SHA3-512")
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate sha3 hash using default variant",
                "sha3(\"foobar\")",
                "ff32a30c3af5012ea395827a3e99a13073c3a8d8410a708568ff7e6eb85968fccfebaea039bc21411e9d43fdb9a851b529b9960ffea8679199781b8f45ca85e2",
                false
            ),
            VRLFunctionExample(
                "Calculate sha3 hash with SHA3-224",
                "sha3(\"foo\", variant: \"SHA3-224\")",
                "f4f6779e153c391bbd29c95e72b0708e39d9166c7cea51d1f10ef58a",
                false
            ),
            VRLFunctionExample(
                "Calculate sha3 hash with SHA3-384",
                "sha3(\"foobar\", \"SHA3-384\")",
                "0fa8abfbdaf924ad307b74dd2ed183b9a4a398891a2f6bac8fd2db7041b77f068580f9c6c66f699b496c2da1cbcc7ed8",
                false
            )
        )
    )
)
