// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val debugFunctions = mapOf(
    "assert" to VRLFunction(
        name = "assert",
        description = "Asserts the <code>condition</code>, which must be a Boolean expression. The program is aborted with <code>message</code> if the condition evaluates to <code>false</code>.",
        isFallible = true,
        isPure = false,
        arguments = listOf(
            VRLFunctionArgument(
                "condition",
                setOf("boolean"),
                "The condition to check.",
                true
            ),
            VRLFunctionArgument(
                "message",
                setOf("string"),
                "An optional custom error message. If the equality assertion fails, <code>message</code> is appended to the default message prefix. See the <a href=\"https://vector.dev/docs/reference/vrl/functions/#assert-examples\">examples</a> below for a fully formed log message sample.",
                false
            )
        ),
        returnTypes = setOf("boolean", "error")
    ),
    "assert_eq" to VRLFunction(
        name = "assert_eq",
        description = "Asserts that two expressions, <code>left</code> and <code>right</code>, have the same value. The program is aborted with <code>message</code> if they do not have the same value.",
        isFallible = false,
        isPure = false,
        arguments = listOf(
            VRLFunctionArgument(
                "left",
                setOf("any"),
                "The value to check for equality against <code>right</code>.",
                true
            ),
            VRLFunctionArgument(
                "right",
                setOf("any"),
                "The value to check for equality against <code>left</code>.",
                true
            ),
            VRLFunctionArgument(
                "message",
                setOf("string"),
                "An optional custom error message. If the equality assertion fails, <code>message</code> is appended to the default message prefix. See the <a href=\"https://vector.dev/docs/reference/vrl/functions/#assert_eq-examples\">examples</a> below for a fully formed log message sample.",
                false
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "log" to VRLFunction(
        name = "log",
        description = "Logs the <code>value</code> to <a href=\"https://en.wikipedia.org/wiki/Standard_streams#Standard_output_%28stdout%29\">stdout</a> at the specified <code>level</code>.",
        isFallible = false,
        isPure = false,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to log.",
                true
            ),
            VRLFunctionArgument(
                "level",
                setOf("string"),
                "The log level.",
                false,
                defaultValue = "info"
            ),
            VRLFunctionArgument(
                "rate_limit_secs",
                setOf("integer"),
                "Specifies that the log message is output no more than once per the given number of seconds. Use a value of <code>0</code> to turn rate limiting off.",
                false,
                defaultValue = 1
            )
        ),
        returnTypes = setOf("null")
    )
)
