// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val enumerateFunctions = mapOf(
    "compact" to VRLFunction(
        name = "compact",
        description = "Compacts the <code>value</code> by removing empty values, where empty values are defined using the available parameters.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to compact.",
                true
            ),
            VRLFunctionArgument(
                "recursive",
                setOf("boolean"),
                "Whether the compaction be recursive.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "null",
                setOf("boolean"),
                "Whether null should be treated as an empty value.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "string",
                setOf("boolean"),
                "Whether an empty string should be treated as an empty value.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "object",
                setOf("boolean"),
                "Whether an empty object should be treated as an empty value.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "array",
                setOf("boolean"),
                "Whether an empty array should be treated as an empty value.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "nullish",
                setOf("boolean"),
                "Tests whether the value is “nullish” as defined by the <a href=\"https://vector.dev/docs/reference/vrl/functions/#is_nullish\"><code>is_nullish</code></a> function.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "array")
    ),
    "filter" to VRLFunction(
        name = "filter",
        description = "<p>Filter elements from a collection.</p>\n\n<p>This function currently <em>does not</em> support recursive iteration.</p>\n\n<p>The function uses the function closure syntax to allow reading the key-value or index-value combination for each item in the collection.</p>\n\n<p>The same scoping rules apply to closure blocks as they do for regular blocks. This means that any variable defined in parent scopes is accessible, and mutations to those variables are preserved, but any new variables instantiated in the closure block are unavailable outside of the block.</p>\n\n<p>See the examples below to learn about the closure syntax.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The array or object to filter.",
                true
            )
        ),
        returnTypes = setOf("object", "array")
    ),
    "flatten" to VRLFunction(
        name = "flatten",
        description = "Flattens the <code>value</code> into a single-level representation.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The array or object to flatten.",
                true
            ),
            VRLFunctionArgument(
                "separator",
                setOf("string"),
                "The separator to join nested keys",
                false,
                defaultValue = "."
            ),
            VRLFunctionArgument(
                "except",
                setOf("array"),
                "An array of key names to exclude from flattening at any depth.",
                false,
                defaultValue = "[]"
            )
        ),
        returnTypes = setOf("object", "array")
    ),
    "for_each" to VRLFunction(
        name = "for_each",
        description = "<p>Iterate over a collection.</p>\n\n<p>This function currently <em>does not</em> support recursive iteration.</p>\n\n<p>The function uses the “function closure syntax” to allow reading the key/value or index/value combination for each item in the collection.</p>\n\n<p>The same scoping rules apply to closure blocks as they do for regular blocks. This means that any variable defined in parent scopes is accessible, and mutations to those variables are preserved, but any new variables instantiated in the closure block are unavailable outside of the block.</p>\n\n<p>See the examples below to learn about the closure syntax.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The array or object to iterate.",
                true
            )
        ),
        returnTypes = setOf("null")
    ),
    "includes" to VRLFunction(
        name = "includes",
        description = "Determines whether the <code>value</code> array includes the specified <code>item</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The array.",
                true
            ),
            VRLFunctionArgument(
                "item",
                setOf("any"),
                "The item to check.",
                true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "keys" to VRLFunction(
        name = "keys",
        description = "Returns the keys from the object passed into the function.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The object to extract keys from.",
                true
            )
        ),
        returnTypes = setOf("array")
    ),
    "length" to VRLFunction(
        name = "length",
        description = "<p>Returns the length of the <code>value</code>.</p><ul><li>If <code>value</code> is an array, returns the number of elements.</li><li>If <code>value</code> is an object, returns the number of top-level keys.</li><li>If <code>value</code> is a string, returns the number of bytes in the string. If you want the number of characters, see <code>strlen</code>.</li></ul>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string", "object", "array"),
                "The array or object.",
                true
            )
        ),
        returnTypes = setOf("integer")
    ),
    "map_keys" to VRLFunction(
        name = "map_keys",
        description = "<p>Map the keys within an object.</p>\n\n<p>If <code>recursive</code> is enabled, the function iterates into nested objects, using the following rules:</p><ol><li>Iteration starts at the root.</li><li>For every nested object type:<ul><li>First return the key of the object type itself.</li><li>Then recurse into the object, and loop back to item (1) in this list.</li><li>Any mutation done on a nested object <em>before</em> recursing into it, are preserved.</li></ul></li><li>For every nested array type:<ul><li>First return the key of the array type itself.</li><li>Then find all objects within the array, and apply item (2) to each individual object.</li></ul></li></ol><p>The above rules mean that <code>map_keys</code> with <code>recursive</code> enabled finds <em>all</em> keys in the target, regardless of whether nested objects are nested inside arrays.</p>\n\n<p>The function uses the function closure syntax to allow reading the key for each item in the object.</p>\n\n<p>The same scoping rules apply to closure blocks as they do for regular blocks. This means that any variable defined in parent scopes is accessible, and mutations to those variables are preserved, but any new variables instantiated in the closure block are unavailable outside of the block.</p>\n\n<p>See the examples below to learn about the closure syntax.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The object to iterate.",
                true
            ),
            VRLFunctionArgument(
                "recursive",
                setOf("boolean"),
                "Whether to recursively iterate the collection.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object")
    ),
    "map_values" to VRLFunction(
        name = "map_values",
        description = "<p>Map the values within a collection.</p>\n\n<p>If <code>recursive</code> is enabled, the function iterates into nested collections, using the following rules:</p><ol><li>Iteration starts at the root.</li><li>For every nested collection type:<ul><li>First return the collection type itself.</li><li>Then recurse into the collection, and loop back to item (1) in the list</li><li>Any mutation done on a collection <em>before</em> recursing into it, are preserved.</li></ul></li></ol><p>The function uses the function closure syntax to allow mutating the value for each item in the collection.</p>\n\n<p>The same scoping rules apply to closure blocks as they do for regular blocks, meaning, any variable defined in parent scopes are accessible, and mutations to those variables are preserved, but any new variables instantiated in the closure block are unavailable outside of the block.</p>\n\n<p>Check out the examples below to learn about the closure syntax.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to iterate.",
                true
            ),
            VRLFunctionArgument(
                "recursive",
                setOf("boolean"),
                "Whether to recursively iterate the collection.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "array")
    ),
    "match_array" to VRLFunction(
        name = "match_array",
        description = "Determines whether the elements in the <code>value</code> array matches the <code>pattern</code>. By default, it checks that at least one element matches, but can be set to determine if all the elements match.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The array.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("regex"),
                "The regular expression pattern to match against.",
                true
            ),
            VRLFunctionArgument(
                "all",
                setOf("boolean"),
                "Whether to match on all elements of <code>value</code>.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "strlen" to VRLFunction(
        name = "strlen",
        description = "<p>Returns the number of UTF-8 characters in <code>value</code>. This differs from <code>length</code> which counts the number of bytes of a string.</p>\n\n<p><strong>Note</strong>: This is the count of <a href=\"https://www.unicode.org/glossary/#unicode_scalar_value\">Unicode scalar values</a> which can sometimes differ from <a href=\"https://www.unicode.org/glossary/#code_point\">Unicode code points</a>.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string.",
                true
            )
        ),
        returnTypes = setOf("integer")
    ),
    "tally" to VRLFunction(
        name = "tally",
        description = "Counts the occurrences of each string value in the provided array and returns an object with the counts.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The array of strings to count occurrences for.",
                true
            )
        ),
        returnTypes = setOf("object")
    ),
    "tally_value" to VRLFunction(
        name = "tally_value",
        description = "Counts the number of times a specific value appears in the provided array.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "array",
                setOf("array"),
                "The array to search through.",
                true
            ),
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to count occurrences of in the array.",
                true
            )
        ),
        returnTypes = setOf("integer")
    ),
    "unflatten" to VRLFunction(
        name = "unflatten",
        description = "Unflattens the <code>value</code> into a nested representation.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The array or object to unflatten.",
                true
            ),
            VRLFunctionArgument(
                "separator",
                setOf("string"),
                "The separator to split flattened keys.",
                false,
                defaultValue = "."
            ),
            VRLFunctionArgument(
                "recursive",
                setOf("boolean"),
                "Whether to recursively unflatten the object values.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("object")
    ),
    "unique" to VRLFunction(
        name = "unique",
        description = "<p>Returns the unique values for an array.</p>\n\n<p>The first occurrence of each element is kept.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The array to return unique elements from.",
                true
            )
        ),
        returnTypes = setOf("array")
    ),
    "values" to VRLFunction(
        name = "values",
        description = "Returns the values from the object passed into the function.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The object to extract values from.",
                true
            )
        ),
        returnTypes = setOf("array")
    )
)
