// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val ipFunctions = mapOf(
    "decrypt_ip" to VRLFunction(
        name = "decrypt_ip",
        description = "<p>Decrypts an IP address that was previously encrypted, restoring the original IP address.</p>\n\n<p>Supported Modes:</p><ul><li>AES128 - Decrypts an IP address that was scrambled using AES-128 encryption. Can transform between IPv4 and IPv6.</li><li>PFX (Prefix-preserving) - Decrypts an IP address that was encrypted with prefix-preserving mode, where network hierarchy was maintained.</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "ip",
                setOf("string"),
                "The encrypted IP address to decrypt (v4 or v6).",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The decryption key in raw bytes (not encoded). Must be the same key that was used for encryption. For AES128 mode, the key must be exactly 16 bytes. For PFX mode, the key must be exactly 32 bytes.",
                true
            ),
            VRLFunctionArgument(
                "mode",
                setOf("string"),
                "The decryption mode to use. Must match the mode used for encryption: either <code>aes128</code> or <code>pfx</code>.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Decrypt IPv4 address with AES128",
                "decrypt_ip!(\"72b9:a747:f2e9:72af:76ca:5866:6dcf:c3b0\", \"sixteen byte key\", \"aes128\")",
                "192.168.1.1",
                false
            ),
            VRLFunctionExample(
                "Decrypt IPv6 address with AES128",
                "decrypt_ip!(\"c0e6:eb35:6887:f554:4c65:8ace:17ca:6c6a\", \"sixteen byte key\", \"aes128\")",
                "2001:db8::1",
                false
            ),
            VRLFunctionExample(
                "Decrypt IPv4 address with prefix-preserving mode",
                "decrypt_ip!(\"33.245.248.61\", \"thirty-two bytes key for pfx use\", \"pfx\")",
                "192.168.1.1",
                false
            ),
            VRLFunctionExample(
                "Decrypt IPv6 address with prefix-preserving mode",
                "decrypt_ip!(\"88bd:d2bf:8865:8c4d:84b:44f6:6077:72c9\", \"thirty-two bytes key for ipv6pfx\", \"pfx\")",
                "2001:db8::1",
                false
            ),
            VRLFunctionExample(
                "Round-trip encryption and decryption",
                "original_ip = \"192.168.1.100\"\nkey = \"sixteen byte key\"\nmode = \"aes128\"\n\nencrypted = encrypt_ip!(original_ip, key, mode)\ndecrypt_ip!(encrypted, key, mode)",
                "192.168.1.100",
                false
            )
        )
    ),
    "encrypt_ip" to VRLFunction(
        name = "encrypt_ip",
        description = "<p>Encrypts an IP address, transforming it into a different valid IP address.</p>\n\n<p>Supported Modes:</p><ul><li>AES128 - Scrambles the entire IP address using AES-128 encryption. Can transform between IPv4 and IPv6.</li><li>PFX (Prefix-preserving) - Maintains network hierarchy by ensuring that IP addresses within the same network are encrypted to addresses that also share a common network. This preserves prefix relationships while providing confidentiality.</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "ip",
                setOf("string"),
                "The IP address to encrypt (v4 or v6).",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The encryption key in raw bytes (not encoded). For AES128 mode, the key must be exactly 16 bytes. For PFX mode, the key must be exactly 32 bytes.",
                true
            ),
            VRLFunctionArgument(
                "mode",
                setOf("string"),
                "The encryption mode to use. Must be either <code>aes128</code> or <code>pfx</code>.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Encrypt IPv4 address with AES128",
                "encrypt_ip!(\"192.168.1.1\", \"sixteen byte key\", \"aes128\")",
                "72b9:a747:f2e9:72af:76ca:5866:6dcf:c3b0",
                false
            ),
            VRLFunctionExample(
                "Encrypt IPv6 address with AES128",
                "encrypt_ip!(\"2001:db8::1\", \"sixteen byte key\", \"aes128\")",
                "c0e6:eb35:6887:f554:4c65:8ace:17ca:6c6a",
                false
            ),
            VRLFunctionExample(
                "Encrypt IPv4 address with prefix-preserving mode",
                "encrypt_ip!(\"192.168.1.1\", \"thirty-two bytes key for pfx use\", \"pfx\")",
                "33.245.248.61",
                false
            ),
            VRLFunctionExample(
                "Encrypt IPv6 address with prefix-preserving mode",
                "encrypt_ip!(\"2001:db8::1\", \"thirty-two bytes key for ipv6pfx\", \"pfx\")",
                "88bd:d2bf:8865:8c4d:84b:44f6:6077:72c9",
                false
            )
        )
    ),
    "ip_aton" to VRLFunction(
        name = "ip_aton",
        description = "<p>Converts IPv4 address in numbers-and-dots notation into network-order bytes represented as an integer.</p>\n\n<p>This behavior mimics <a href=\"https://linux.die.net/man/3/inet_aton\">inet_aton</a>.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address to convert to binary.",
                true
            )
        ),
        returnTypes = setOf("integer", "error"),
        examples = listOf(
            VRLFunctionExample(
                "IPv4 to integer",
                "ip_aton!(\"1.2.3.4\")",
                "16909060",
                false
            )
        )
    ),
    "ip_cidr_contains" to VRLFunction(
        name = "ip_cidr_contains",
        description = "Determines whether the <code>ip</code> is contained in the block referenced by the <code>cidr</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "cidr",
                setOf("string", "array"),
                "The CIDR mask (v4 or v6).",
                true
            ),
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address (v4 or v6).",
                true
            )
        ),
        returnTypes = setOf("boolean", "error"),
        examples = listOf(
            VRLFunctionExample(
                "IPv4 contains CIDR",
                "ip_cidr_contains!(\"192.168.0.0/16\", \"192.168.10.32\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "IPv4 is private",
                "ip_cidr_contains!([\"10.0.0.0/8\", \"172.16.0.0/12\", \"192.168.0.0/16\"], \"192.168.10.32\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "IPv6 contains CIDR",
                "ip_cidr_contains!(\"2001:4f8:4:ba::/64\", \"2001:4f8:4:ba:2e0:81ff:fe22:d1f1\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Not in range",
                "ip_cidr_contains!(\"192.168.0.0/24\", \"192.168.10.32\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Invalid address",
                "ip_cidr_contains!(\"192.168.0.0/24\", \"INVALID\")",
                "function call error for \"ip_cidr_contains\" at (0:46): unable to parse IP address: invalid IP address syntax",
                true
            )
        )
    ),
    "ip_ntoa" to VRLFunction(
        name = "ip_ntoa",
        description = "<p>Converts numeric representation of IPv4 address in network-order bytes to numbers-and-dots notation.</p>\n\n<p>This behavior mimics <a href=\"https://linux.die.net/man/3/inet_ntoa\">inet_ntoa</a>.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The integer representation of an IPv4 address.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Integer to IPv4",
                "ip_ntoa!(16909060)",
                "1.2.3.4",
                false
            )
        )
    ),
    "ip_ntop" to VRLFunction(
        name = "ip_ntop",
        description = "<p>Converts IPv4 and IPv6 addresses from binary to text form.</p>\n\n<p>This behavior mimics <a href=\"https://linux.die.net/man/3/inet_ntop\">inet_ntop</a>.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The binary data to convert from. For IPv4 addresses, it must be 4 bytes (32 bits) long. For IPv6 addresses, it must be 16 bytes (128 bits) long.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Convert IPv4 address from bytes after decoding from Base64",
                "ip_ntop!(decode_base64!(\"wKgAAQ==\"))",
                "192.168.0.1",
                false
            ),
            VRLFunctionExample(
                "Convert IPv6 address from bytes after decoding from Base64",
                "ip_ntop!(decode_base64!(\"IAENuIWjAAAAAIouA3BzNA==\"))",
                "2001:db8:85a3::8a2e:370:7334",
                false
            )
        )
    ),
    "ip_pton" to VRLFunction(
        name = "ip_pton",
        description = "<p>Converts IPv4 and IPv6 addresses from text to binary form.</p><ul><li>The binary form of IPv4 addresses is 4 bytes (32 bits) long.</li><li>The binary form of IPv6 addresses is 16 bytes (128 bits) long.</li></ul><p>This behavior mimics <a href=\"https://linux.die.net/man/3/inet_pton\">inet_pton</a>.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address (v4 or v6) to convert to binary form.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Convert IPv4 address to bytes and encode to Base64",
                "encode_base64(ip_pton!(\"192.168.0.1\"))",
                "wKgAAQ==",
                false
            ),
            VRLFunctionExample(
                "Convert IPv6 address to bytes and encode to Base64",
                "encode_base64(ip_pton!(\"2001:db8:85a3::8a2e:370:7334\"))",
                "IAENuIWjAAAAAIouA3BzNA==",
                false
            )
        )
    ),
    "ip_subnet" to VRLFunction(
        name = "ip_subnet",
        description = "Extracts the subnet address from the <code>ip</code> using the supplied <code>subnet</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address (v4 or v6).",
                true
            ),
            VRLFunctionArgument(
                "subnet",
                setOf("string"),
                "The subnet to extract from the IP address. This can be either a prefix length like <code>/8</code> or a net mask like <code>255.255.0.0</code>. The net mask can be either an IPv4 or IPv6 address.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "IPv4 subnet",
                "ip_subnet!(\"192.168.10.32\", \"255.255.255.0\")",
                "192.168.10.0",
                false
            ),
            VRLFunctionExample(
                "IPv6 subnet",
                "ip_subnet!(\"2404:6800:4003:c02::64\", \"/32\")",
                "2404:6800::",
                false
            ),
            VRLFunctionExample(
                "Subnet /1",
                "ip_subnet!(\"192.168.0.1\", \"/1\")",
                "128.0.0.0",
                false
            )
        )
    ),
    "ip_to_ipv6" to VRLFunction(
        name = "ip_to_ipv6",
        description = "Converts the <code>ip</code> to an IPv6 address.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address to convert to IPv6.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "IPv4 to IPv6",
                "ip_to_ipv6!(\"192.168.10.32\")",
                "::ffff:192.168.10.32",
                false
            )
        )
    ),
    "ipv6_to_ipv4" to VRLFunction(
        name = "ipv6_to_ipv4",
        description = "Converts the <code>ip</code> to an IPv4 address. <code>ip</code> is returned unchanged if it’s already an IPv4 address. If <code>ip</code> is currently an IPv6 address then it needs to be IPv4 compatible, otherwise an error is thrown.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IPv4-mapped IPv6 address to convert.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "IPv6 to IPv4",
                "ipv6_to_ipv4!(\"::ffff:192.168.0.1\")",
                "192.168.0.1",
                false
            )
        )
    ),
    "is_ipv4" to VRLFunction(
        name = "is_ipv4",
        description = "<p>Check if the string is a valid IPv4 address or not.</p>\n\n<p>An <a href=\"https://datatracker.ietf.org/doc/html/rfc6890\">IPv4-mapped</a> or <a href=\"https://datatracker.ietf.org/doc/html/rfc6890\">IPv4-compatible</a> IPv6 address is not considered valid for the purpose of this function.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address to check",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid IPv4 address",
                "is_ipv4(\"10.0.102.37\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Valid IPv6 address",
                "is_ipv4(\"2001:0db8:85a3:0000:0000:8a2e:0370:7334\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Arbitrary string",
                "is_ipv4(\"foobar\")",
                "false",
                false
            )
        )
    ),
    "is_ipv6" to VRLFunction(
        name = "is_ipv6",
        description = "Check if the string is a valid IPv6 address or not.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address to check",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid IPv6 address",
                "is_ipv6(\"2001:0db8:85a3:0000:0000:8a2e:0370:7334\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Valid IPv4 address",
                "is_ipv6(\"10.0.102.37\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Arbitrary string",
                "is_ipv6(\"foobar\")",
                "false",
                false
            )
        )
    )
)
