// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val mapFunctions = mapOf(
    "haversine" to VRLFunction(
        name = "haversine",
        description = "Calculates <a href=\"https://en.wikipedia.org/wiki/Haversine_formula\">haversine</a> distance and bearing between two points.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "latitude1",
                setOf("float"),
                "Latitude of the first point.",
                true
            ),
            VRLFunctionArgument(
                "longitude1",
                setOf("float"),
                "Longitude of the first point.",
                true
            ),
            VRLFunctionArgument(
                "latitude2",
                setOf("float"),
                "Latitude of the second point.",
                true
            ),
            VRLFunctionArgument(
                "longitude2",
                setOf("float"),
                "Longitude of the second point.",
                true
            ),
            VRLFunctionArgument(
                "measurement_unit",
                setOf("string"),
                "Measurement system to use for resulting distance.",
                false
            )
        ),
        returnTypes = setOf("object"),
        examples = listOf(
            VRLFunctionExample(
                "Haversine in kilometers",
                "haversine(0.0, 0.0, 10.0, 10.0)",
                "{\n  \"bearing\": 44.561,\n  \"distance\": 1568.5227233\n}",
                false
            ),
            VRLFunctionExample(
                "Haversine in miles",
                "haversine(0.0, 0.0, 10.0, 10.0, measurement_unit: \"miles\")",
                "{\n  \"bearing\": 44.561,\n  \"distance\": 974.6348468\n}",
                false
            )
        )
    )
)
