// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val metricsFunctions = mapOf(
    "aggregate_vector_metrics" to VRLFunction(
        name = "aggregate_vector_metrics",
        description = "<p>Aggregates internal Vector metrics, using one of 4 aggregation functions, filtering by name and optionally by tags. Returns the aggregated value. Only includes counter and gauge metrics.</p>\n\n<p>Internal Vector metrics functions work with a snapshot of the metrics. The interval at which the snapshot is updated is controlled through the <a href=\"https://vector.dev/docs/reference/configuration/global-options/#metrics_storage_refresh_period\"><code>metrics_storage_refresh_period</code></a> global option. Higher values can reduce performance impact of that process, but may cause stale metrics data in the snapshot.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "function",
                setOf("string"),
                "The aggregation function to apply to the matched metrics.",
                true
            ),
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The metric name to aggregate.",
                true
            ),
            VRLFunctionArgument(
                "tags",
                setOf("object"),
                "Tags to filter the results on. Values in this object support wildcards (’*’) to match on parts of the tag value.",
                false,
                defaultValue = "{ }"
            )
        ),
        returnTypes = setOf("float", "null"),
        examples = listOf(
            VRLFunctionExample(
                "Sum vector internal metrics matching the name",
                "aggregate_vector_metrics(\"sum\", \"utilization\")",
                "0.5",
                false
            ),
            VRLFunctionExample(
                "Sum vector internal metrics matching the name and tags",
                "aggregate_vector_metrics(\"sum\", \"utilization\", tags: {\"component_id\": \"test\"})",
                "0.5",
                false
            ),
            VRLFunctionExample(
                "Average of vector internal metrics matching the name",
                "aggregate_vector_metrics(\"avg\", \"utilization\")",
                "0.5",
                false
            ),
            VRLFunctionExample(
                "Max of vector internal metrics matching the name",
                "aggregate_vector_metrics(\"max\", \"utilization\")",
                "0.5",
                false
            ),
            VRLFunctionExample(
                "Min of vector internal metrics matching the name",
                "aggregate_vector_metrics(\"min\", \"utilization\")",
                "0.5",
                false
            )
        )
    ),
    "find_vector_metrics" to VRLFunction(
        name = "find_vector_metrics",
        description = "<p>Searches internal Vector metrics by name and optionally by tags. Returns all matching metrics.</p>\n\n<p>Internal Vector metrics functions work with a snapshot of the metrics. The interval at which the snapshot is updated is controlled through the <a href=\"https://vector.dev/docs/reference/configuration/global-options/#metrics_storage_refresh_period\"><code>metrics_storage_refresh_period</code></a> global option. Higher values can reduce performance impact of that process, but may cause stale metrics data in the snapshot.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The metric name to search.",
                true
            ),
            VRLFunctionArgument(
                "tags",
                setOf("object"),
                "Tags to filter the results on. Values in this object support wildcards (’*’) to match on parts of the tag value.",
                false,
                defaultValue = "{ }"
            )
        ),
        returnTypes = setOf("array"),
        examples = listOf(
            VRLFunctionExample(
                "Find vector internal metrics matching the name",
                "find_vector_metrics(\"utilization\")",
                "[{\"kind\":\"absolute\",\"name\":\"utilization\",\"tags\":{\"component_id\":[\"test\"]},\"type\":\"gauge\",\"value\":0.5}]",
                false
            ),
            VRLFunctionExample(
                "Find vector internal metrics matching the name and tags",
                "find_vector_metrics(\"utilization\", tags: {\"component_id\": \"test\"})",
                "[{\"kind\":\"absolute\",\"name\":\"utilization\",\"tags\":{\"component_id\":[\"test\"]},\"type\":\"gauge\",\"value\":0.5}]",
                false
            )
        )
    ),
    "get_vector_metric" to VRLFunction(
        name = "get_vector_metric",
        description = "<p>Searches internal Vector metrics by name and optionally by tags. Returns the first matching metric.</p>\n\n<p>Internal Vector metrics functions work with a snapshot of the metrics. The interval at which the snapshot is updated is controlled through the <a href=\"https://vector.dev/docs/reference/configuration/global-options/#metrics_storage_refresh_period\"><code>metrics_storage_refresh_period</code></a> global option. Higher values can reduce performance impact of that process, but may cause stale metrics data in the snapshot.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "key",
                setOf("string"),
                "The metric name to search.",
                true
            ),
            VRLFunctionArgument(
                "tags",
                setOf("object"),
                "Tags to filter the results on. Values in this object support wildcards (’*’) to match on parts of the tag value.",
                false,
                defaultValue = "{ }"
            )
        ),
        returnTypes = setOf("object", "null"),
        examples = listOf(
            VRLFunctionExample(
                "Get a vector internal metric matching the name",
                "get_vector_metric(\"utilization\")",
                "{\n  \"kind\": \"absolute\",\n  \"name\": \"utilization\",\n  \"tags\": {\n    \"component_id\": [\n      \"test\"\n    ]\n  },\n  \"type\": \"gauge\",\n  \"value\": 0.5\n}",
                false
            ),
            VRLFunctionExample(
                "Get a vector internal metric matching the name and tags",
                "get_vector_metric(\"utilization\", tags: {\"component_id\": \"test\"})",
                "{\n  \"kind\": \"absolute\",\n  \"name\": \"utilization\",\n  \"tags\": {\n    \"component_id\": [\n      \"test\"\n    ]\n  },\n  \"type\": \"gauge\",\n  \"value\": 0.5\n}",
                false
            )
        )
    )
)
