// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val numberFunctions = mapOf(
    "abs" to VRLFunction(
        name = "abs",
        description = "Computes the absolute value of <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to calculate the absolute value.",
                true
            )
        ),
        returnTypes = setOf("integer", "float"),
        examples = listOf(
            VRLFunctionExample(
                "Computes the absolute value of an integer",
                "abs(-42)",
                "42",
                false
            ),
            VRLFunctionExample(
                "Computes the absolute value of a float",
                "abs(-42.2)",
                "42.2",
                false
            ),
            VRLFunctionExample(
                "Computes the absolute value of a positive integer",
                "abs(10)",
                "10",
                false
            )
        )
    ),
    "ceil" to VRLFunction(
        name = "ceil",
        description = "Rounds the <code>value</code> up to the specified <code>precision</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to round up.",
                true
            ),
            VRLFunctionArgument(
                "precision",
                setOf("integer"),
                "The number of decimal places to round to.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "float"),
        examples = listOf(
            VRLFunctionExample(
                "Round a number up (without precision)",
                "ceil(4.345)",
                "5",
                false
            ),
            VRLFunctionExample(
                "Round a number up (with precision)",
                "ceil(4.345, precision: 2)",
                "4.35",
                false
            ),
            VRLFunctionExample(
                "Round an integer up (noop)",
                "ceil(5)",
                "5",
                false
            )
        )
    ),
    "floor" to VRLFunction(
        name = "floor",
        description = "Rounds the <code>value</code> down to the specified <code>precision</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to round down.",
                true
            ),
            VRLFunctionArgument(
                "precision",
                setOf("integer"),
                "The number of decimal places to round to.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "float"),
        examples = listOf(
            VRLFunctionExample(
                "Round a number down (without precision)",
                "floor(9.8)",
                "9",
                false
            ),
            VRLFunctionExample(
                "Round a number down (with precision)",
                "floor(4.345, precision: 2)",
                "4.34",
                false
            )
        )
    ),
    "format_int" to VRLFunction(
        name = "format_int",
        description = "Formats the integer <code>value</code> into a string representation using the given base/radix.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The number to format.",
                true
            ),
            VRLFunctionArgument(
                "base",
                setOf("integer"),
                "The base to format the number in. Must be between 2 and 36 (inclusive).",
                false,
                defaultValue = 10
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Format as a hexadecimal integer",
                "format_int!(42, 16)",
                "2a",
                false
            ),
            VRLFunctionExample(
                "Format as a negative hexadecimal integer",
                "format_int!(-42, 16)",
                "-2a",
                false
            ),
            VRLFunctionExample(
                "Format as a decimal integer (default base)",
                "format_int!(42)",
                "42",
                false
            )
        )
    ),
    "format_number" to VRLFunction(
        name = "format_number",
        description = "Formats the <code>value</code> into a string representation of the number.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to format as a string.",
                true
            ),
            VRLFunctionArgument(
                "scale",
                setOf("integer"),
                "The number of decimal places to display.",
                false
            ),
            VRLFunctionArgument(
                "decimal_separator",
                setOf("string"),
                "The character to use between the whole and decimal parts of the number.",
                false,
                defaultValue = "."
            ),
            VRLFunctionArgument(
                "grouping_separator",
                setOf("string"),
                "The character to use between each thousands part of the number.",
                false
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Format a number (3 decimals)",
                "format_number(1234567.89, 3, decimal_separator: \".\", grouping_separator: \",\")",
                "1,234,567.890",
                false
            ),
            VRLFunctionExample(
                "Format a number with European-style separators",
                "format_number(4672.4, decimal_separator: \",\", grouping_separator: \"_\")",
                "4_672,4",
                false
            ),
            VRLFunctionExample(
                "Format a number with a middle dot separator",
                "format_number(4321.09, 3, decimal_separator: \"·\")",
                "4321·090",
                false
            )
        )
    ),
    "mod" to VRLFunction(
        name = "mod",
        description = "Calculates the remainder of <code>value</code> divided by <code>modulus</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The value the <code>modulus</code> is applied to.",
                true
            ),
            VRLFunctionArgument(
                "modulus",
                setOf("integer", "float"),
                "The <code>modulus</code> value.",
                true
            )
        ),
        returnTypes = setOf("integer", "float", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Calculate the remainder of two integers",
                "mod(5, 2)",
                "1",
                false
            )
        )
    ),
    "round" to VRLFunction(
        name = "round",
        description = "Rounds the <code>value</code> to the specified <code>precision</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to round.",
                true
            ),
            VRLFunctionArgument(
                "precision",
                setOf("integer"),
                "The number of decimal places to round to.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "float"),
        examples = listOf(
            VRLFunctionExample(
                "Round a number (without precision)",
                "round(4.345)",
                "4",
                false
            ),
            VRLFunctionExample(
                "Round a number (with precision)",
                "round(4.345, precision: 2)",
                "4.35",
                false
            ),
            VRLFunctionExample(
                "Round up",
                "round(5.5)",
                "6",
                false
            ),
            VRLFunctionExample(
                "Round down",
                "round(5.45)",
                "5",
                false
            )
        )
    )
)
