// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val numberFunctions = mapOf(
    "abs" to VRLFunction(
        name = "abs",
        description = "Computes the absolute value of <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to calculate the absolute value.",
                true
            )
        ),
        returnTypes = setOf("integer", "float")
    ),
    "ceil" to VRLFunction(
        name = "ceil",
        description = "Rounds the <code>value</code> up to the specified <code>precision</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to round up.",
                true
            ),
            VRLFunctionArgument(
                "precision",
                setOf("integer"),
                "The number of decimal places to round to.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "float")
    ),
    "floor" to VRLFunction(
        name = "floor",
        description = "Rounds the <code>value</code> down to the specified <code>precision</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to round down.",
                true
            ),
            VRLFunctionArgument(
                "precision",
                setOf("integer"),
                "The number of decimal places to round to.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "float")
    ),
    "format_int" to VRLFunction(
        name = "format_int",
        description = "Formats the integer <code>value</code> into a string representation using the given base/radix.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer"),
                "The number to format.",
                true
            ),
            VRLFunctionArgument(
                "base",
                setOf("integer"),
                "The base to format the number in. Must be between 2 and 36 (inclusive).",
                false,
                defaultValue = 10
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "format_number" to VRLFunction(
        name = "format_number",
        description = "Formats the <code>value</code> into a string representation of the number.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to format as a string.",
                true
            ),
            VRLFunctionArgument(
                "scale",
                setOf("integer"),
                "The number of decimal places to display.",
                false
            ),
            VRLFunctionArgument(
                "decimal_separator",
                setOf("string"),
                "The character to use between the whole and decimal parts of the number.",
                false,
                defaultValue = "."
            ),
            VRLFunctionArgument(
                "grouping_separator",
                setOf("string"),
                "The character to use between each thousands part of the number.",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "mod" to VRLFunction(
        name = "mod",
        description = "Calculates the remainder of <code>value</code> divided by <code>modulus</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The value the <code>modulus</code> is applied to.",
                true
            ),
            VRLFunctionArgument(
                "modulus",
                setOf("integer", "float"),
                "The <code>modulus</code> value.",
                true
            )
        ),
        returnTypes = setOf("integer", "float", "error")
    ),
    "round" to VRLFunction(
        name = "round",
        description = "Rounds the <code>value</code> to the specified <code>precision</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("integer", "float"),
                "The number to round.",
                true
            ),
            VRLFunctionArgument(
                "precision",
                setOf("integer"),
                "The number of decimal places to round to.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "float")
    )
)
