// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val objectFunctions = mapOf(
    "from_entries" to VRLFunction(
        name = "from_entries",
        description = "Converts array of key/value objects into an object.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The array of key/value objects to convert.",
                true
            )
        ),
        returnTypes = setOf("object")
    ),
    "match_datadog_query" to VRLFunction(
        name = "match_datadog_query",
        description = "Matches an object against a <a href=\"https://docs.datadoghq.com/logs/explorer/search_syntax/\">Datadog Search Syntax</a> query.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object"),
                "The object.",
                true
            ),
            VRLFunctionArgument(
                "query",
                setOf("string"),
                "The Datadog Search Syntax query.",
                true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "merge" to VRLFunction(
        name = "merge",
        description = "Merges the <code>from</code> object into the <code>to</code> object.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "to",
                setOf("object"),
                "The object to merge into.",
                true
            ),
            VRLFunctionArgument(
                "from",
                setOf("object"),
                "The object to merge from.",
                true
            ),
            VRLFunctionArgument(
                "deep",
                setOf("boolean"),
                "A deep merge is performed if <code>true</code>, otherwise only top-level fields are merged.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object")
    ),
    "object_from_array" to VRLFunction(
        name = "object_from_array",
        description = "<p>Iterate over either one array of arrays or a pair of arrays and create an object out of all the key-value pairs contained in them. With one array of arrays, any entries with no value use <code>null</code> instead. Any keys that are <code>null</code> skip the corresponding value.</p>\n\n<p>If a single parameter is given, it must contain an array of all the input arrays.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "values",
                setOf("array"),
                "The first array of elements, or the array of input arrays if no other parameter is present.",
                true
            ),
            VRLFunctionArgument(
                "keys",
                setOf("array"),
                "The second array of elements. If not present, the first parameter must contain all the arrays.",
                false
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "to_entries" to VRLFunction(
        name = "to_entries",
        description = "Converts JSON objects or arrays into array of objects.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to manipulate.",
                true
            )
        ),
        returnTypes = setOf("array")
    ),
    "unnest" to VRLFunction(
        name = "unnest",
        description = "<p>Unnest an array field from an object to create an array of objects using that field; keeping all other fields.</p>\n\n<p>Assigning the array result of this to <code>.</code> results in multiple events being emitted from <code>remap</code>. See the <a href=\"https://vector.dev/docs/reference/configuration/transforms/remap/#emitting-multiple-log-events\"><code>remap</code> transform docs</a> for more details.</p>\n\n<p>This is also referred to as <code>explode</code> in some languages.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "The path of the field to unnest.",
                true
            )
        ),
        returnTypes = setOf("array", "error")
    )
)
