// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val parseFunctions = mapOf(
    "parse_apache_log" to VRLFunction(
        name = "parse_apache_log",
        description = "Parses Apache access and error log lines. Lines can be in <a href=\"https://httpd.apache.org/docs/current/logs.html#common\"><code>common</code></a>, <a href=\"https://httpd.apache.org/docs/current/logs.html#combined\"><code>combined</code></a>, or the default <a href=\"https://httpd.apache.org/docs/current/logs.html#errorlog\"><code>error</code></a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "format",
                setOf("string"),
                "The format to use for parsing the log.",
                true
            ),
            VRLFunctionArgument(
                "timestamp_format",
                setOf("string"),
                "The <a href=\"https://docs.rs/chrono/latest/chrono/format/strftime/index.html\">date/time format</a> to use for encoding the timestamp. The time is parsed in local time if the timestamp does not specify a timezone.",
                false,
                defaultValue = "%d/%b/%Y:%T %z"
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_aws_alb_log" to VRLFunction(
        name = "parse_aws_alb_log",
        description = "Parses <code>value</code> in the <a href=\"https://docs.aws.amazon.com/elasticloadbalancing/latest/application/load-balancer-access-logs.html#access-log-entry-examples\">Elastic Load Balancer Access format</a>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "Access log of the Application Load Balancer.",
                true
            ),
            VRLFunctionArgument(
                "strict_mode",
                setOf("boolean"),
                "When set to <code>false</code>, the parser ignores any newly added or trailing fields in AWS ALB logs instead of failing. Defaults to <code>true</code> to preserve strict parsing behavior.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_aws_cloudwatch_log_subscription_message" to VRLFunction(
        name = "parse_aws_cloudwatch_log_subscription_message",
        description = "Parses AWS CloudWatch Logs events (configured through AWS Cloudwatch subscriptions) from the <code>aws_kinesis_firehose</code> source.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string representation of the message to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_aws_vpc_flow_log" to VRLFunction(
        name = "parse_aws_vpc_flow_log",
        description = "Parses <code>value</code> in the <a href=\"https://docs.aws.amazon.com/vpc/latest/userguide/flow-logs.html\">VPC Flow Logs format</a>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "VPC Flow Log.",
                true
            ),
            VRLFunctionArgument(
                "format",
                setOf("string"),
                "VPC Flow Log format.",
                false
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_bytes" to VRLFunction(
        name = "parse_bytes",
        description = "Parses the <code>value</code> into a human-readable bytes format specified by <code>unit</code> and <code>base</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string of the duration with either binary or SI unit.",
                true
            ),
            VRLFunctionArgument(
                "unit",
                setOf("string"),
                "The output units for the byte.",
                true
            ),
            VRLFunctionArgument(
                "base",
                setOf("string"),
                "The base for the byte, either 2 or 10.",
                false,
                defaultValue = "2"
            )
        ),
        returnTypes = setOf("float", "error")
    ),
    "parse_cbor" to VRLFunction(
        name = "parse_cbor",
        description = "Parses the <code>value</code> as <a href=\"https://cbor.io\">CBOR</a>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The CBOR payload to parse.",
                true
            )
        ),
        returnTypes = setOf("string", "integer", "float", "boolean", "object", "array", "null", "error")
    ),
    "parse_cef" to VRLFunction(
        name = "parse_cef",
        description = "Parses the <code>value</code> in CEF (Common Event Format) format. Ignores everything up to CEF header. Empty values are returned as empty strings. Surrounding quotes are removed from values.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "translate_custom_fields",
                setOf("boolean"),
                "Toggles translation of custom field pairs to <code>key:value</code>.",
                false,
                defaultValue = false
            ),
            VRLFunctionArgument(
                "strict",
                setOf("boolean"),
                "When set to <code>false</code>, attempts best-effort parsing of malformed CEF input rather than failing.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_common_log" to VRLFunction(
        name = "parse_common_log",
        description = "Parses the <code>value</code> using the <a href=\"https://httpd.apache.org/docs/current/logs.html#common\">Common Log Format</a> (CLF).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "timestamp_format",
                setOf("string"),
                "The <a href=\"https://docs.rs/chrono/latest/chrono/format/strftime/index.html\">date/time format</a> to use for encoding the timestamp.",
                false,
                defaultValue = "%d/%b/%Y:%T %z"
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_csv" to VRLFunction(
        name = "parse_csv",
        description = "Parses a single CSV formatted row. Only the first row is parsed in case of multiline input value.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "delimiter",
                setOf("string"),
                "The field delimiter to use when parsing. Must be a single-byte UTF-8 character.",
                false,
                defaultValue = ","
            )
        ),
        returnTypes = setOf("array", "error")
    ),
    "parse_dnstap" to VRLFunction(
        name = "parse_dnstap",
        description = "Parses the <code>value</code> as base64 encoded DNSTAP data.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The base64 encoded representation of the DNSTAP data to parse.",
                true
            ),
            VRLFunctionArgument(
                "lowercase_hostnames",
                setOf("boolean"),
                "Whether to turn all hostnames found in resulting data lowercase, for consistency.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_duration" to VRLFunction(
        name = "parse_duration",
        description = "Parses the <code>value</code> into a human-readable duration format specified by <code>unit</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string of the duration.",
                true
            ),
            VRLFunctionArgument(
                "unit",
                setOf("string"),
                "The output units for the duration.",
                true
            )
        ),
        returnTypes = setOf("float", "error")
    ),
    "parse_etld" to VRLFunction(
        name = "parse_etld",
        description = "Parses the <a href=\"https://developer.mozilla.org/en-US/docs/Glossary/eTLD\">eTLD</a> from <code>value</code> representing domain name.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The domain string.",
                true
            ),
            VRLFunctionArgument(
                "plus_parts",
                setOf("integer"),
                "Can be provided to get additional parts of the domain name. When 1 is passed, eTLD+1 will be returned, which represents a domain registrable by a single organization. Higher numbers will return subdomains.",
                false,
                defaultValue = 0
            ),
            VRLFunctionArgument(
                "psl",
                setOf("string"),
                "<p>Can be provided to use a different public suffix list.</p><p>By default, <a href=\"https://publicsuffix.org/list/public_suffix_list.dat\">https://publicsuffix.org/list/public_suffix_list.dat</a> is used.</p>",
                false
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_glog" to VRLFunction(
        name = "parse_glog",
        description = "Parses the <code>value</code> using the <a href=\"https://github.com/google/glog\">glog (Google Logging Library)</a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_grok" to VRLFunction(
        name = "parse_grok",
        description = "Parses the <code>value</code> using the <a href=\"https://github.com/daschl/grok/tree/master/patterns\"><code>grok</code></a> format. All patterns <a href=\"https://github.com/daschl/grok/tree/master/patterns\">listed here</a> are supported.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("string"),
                "The <a href=\"https://github.com/daschl/grok/tree/master/patterns\">Grok pattern</a>.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_groks" to VRLFunction(
        name = "parse_groks",
        description = "Parses the <code>value</code> using multiple <a href=\"https://github.com/daschl/grok/tree/master/patterns\"><code>grok</code></a> patterns. All patterns <a href=\"https://github.com/daschl/grok/tree/master/patterns\">listed here</a> are supported.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "patterns",
                setOf("array"),
                "The <a href=\"https://github.com/daschl/grok/tree/master/patterns\">Grok patterns</a>, which are tried in order until the first match.",
                true
            ),
            VRLFunctionArgument(
                "aliases",
                setOf("object"),
                "The shared set of grok aliases that can be referenced in the patterns to simplify them.",
                false,
                defaultValue = "{ }"
            ),
            VRLFunctionArgument(
                "alias_sources",
                setOf("array"),
                "Path to the file containing aliases in a JSON format.",
                false,
                defaultValue = "[]"
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_influxdb" to VRLFunction(
        name = "parse_influxdb",
        description = "Parses the <code>value</code> as an <a href=\"https://docs.influxdata.com/influxdb/cloud/reference/syntax/line-protocol/\">InfluxDB line protocol</a> string, producing a list of Vector-compatible metrics.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string representation of the InfluxDB line protocol to parse.",
                true
            )
        ),
        returnTypes = setOf("array", "error")
    ),
    "parse_int" to VRLFunction(
        name = "parse_int",
        description = "Parses the string <code>value</code> representing a number in an optional base/radix to an integer.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "base",
                setOf("integer"),
                "<p>The base the number is in. Must be between 2 and 36 (inclusive).</p><p>If unspecified, the string prefix is used to determine the base: “0b”, 8 for “0” or “0o”, 16 for “0x”, and 10 otherwise.</p>",
                false
            )
        ),
        returnTypes = setOf("integer", "error")
    ),
    "parse_json" to VRLFunction(
        name = "parse_json",
        description = "<p>Parses the provided <code>value</code> as JSON.</p>\n\n<p>Only JSON types are returned. If you need to convert a <code>string</code> into a <code>timestamp</code>, consider the <code>parse_timestamp</code> function.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string representation of the JSON to parse.",
                true
            ),
            VRLFunctionArgument(
                "max_depth",
                setOf("integer"),
                "Number of layers to parse for nested JSON-formatted documents. The value must be in the range of 1 to 128.",
                false
            ),
            VRLFunctionArgument(
                "lossy",
                setOf("boolean"),
                "Whether to parse the JSON in a lossy manner. Replaces invalid UTF-8 characters with the Unicode character <code>�</code> (U+FFFD) if set to true, otherwise returns an error if there are any invalid UTF-8 characters present.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("string", "integer", "float", "boolean", "object", "array", "null", "error")
    ),
    "parse_key_value" to VRLFunction(
        name = "parse_key_value",
        description = "<p>Parses the <code>value</code> in key-value format. Also known as <a href=\"https://brandur.org/logfmt\">logfmt</a>.</p><ul><li>Keys and values can be wrapped with <code>\"</code>.</li><li><code>\"</code> characters can be escaped using <code>\\</code>.</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "key_value_delimiter",
                setOf("string"),
                "The string that separates the key from the value.",
                false,
                defaultValue = "="
            ),
            VRLFunctionArgument(
                "field_delimiter",
                setOf("string"),
                "The string that separates each key-value pair.",
                false,
                defaultValue = ""
            ),
            VRLFunctionArgument(
                "whitespace",
                setOf("string"),
                "Defines the acceptance of unnecessary whitespace surrounding the configured <code>key_value_delimiter</code>.",
                false,
                defaultValue = "lenient"
            ),
            VRLFunctionArgument(
                "accept_standalone_key",
                setOf("boolean"),
                "Whether a standalone key should be accepted, the resulting object associates such keys with the boolean value <code>true</code>.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_klog" to VRLFunction(
        name = "parse_klog",
        description = "Parses the <code>value</code> using the <a href=\"https://github.com/kubernetes/klog\">klog</a> format used by Kubernetes components.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_linux_authorization" to VRLFunction(
        name = "parse_linux_authorization",
        description = "Parses Linux authorization logs usually found under either <code>/var/log/auth.log</code> (for Debian-based systems) or <code>/var/log/secure</code> (for RedHat-based systems) according to <a href=\"https://en.wikipedia.org/wiki/Syslog\">Syslog</a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The text containing the message to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_logfmt" to VRLFunction(
        name = "parse_logfmt",
        description = "<p>Parses the <code>value</code> in <a href=\"https://brandur.org/logfmt\">logfmt</a>.</p><ul><li>Keys and values can be wrapped using the <code>\"</code> character.</li><li><code>\"</code> characters can be escaped by the <code>\\</code> character.</li><li>As per this <a href=\"https://pkg.go.dev/github.com/kr/logfmt#section-documentation\">logfmt specification</a>, the <code>parse_logfmt</code> function accepts standalone keys and assigns them a Boolean value of <code>true</code>.</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_nginx_log" to VRLFunction(
        name = "parse_nginx_log",
        description = "Parses Nginx access and error log lines. Lines can be in <a href=\"https://nginx.org/en/docs/http/ngx_http_log_module.html\"><code>combined</code></a>, <a href=\"https://kubernetes.github.io/ingress-nginx/user-guide/nginx-configuration/log-format/\"><code>ingress_upstreaminfo</code></a>, <a href=\"https://hg.nginx.org/pkg-oss/file/tip/debian/debian/nginx.conf\"><code>main</code></a> or <a href=\"https://github.com/nginx/nginx/blob/branches/stable-1.18/src/core/ngx_log.c#L102\"><code>error</code></a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "format",
                setOf("string"),
                "The format to use for parsing the log.",
                true
            ),
            VRLFunctionArgument(
                "timestamp_format",
                setOf("string"),
                "The <a href=\"https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers\">date/time format</a> to use for encoding the timestamp. The time is parsed in local time if the timestamp doesn’t specify a timezone. The default format is <code>%d/%b/%Y:%T %z</code> for combined logs and <code>%Y/%m/%d %H:%M:%S</code> for error logs.",
                false,
                defaultValue = "%d/%b/%Y:%T %z"
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_proto" to VRLFunction(
        name = "parse_proto",
        description = "Parses the <code>value</code> as a protocol buffer payload.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The protocol buffer payload to parse.",
                true
            ),
            VRLFunctionArgument(
                "desc_file",
                setOf("string"),
                "<p>The path to the protobuf descriptor set file. Must be a literal string.</p><p>This file is the output of protoc -o …</p>",
                true
            ),
            VRLFunctionArgument(
                "message_type",
                setOf("string"),
                "<p>The name of the message type to use for serializing.</p><p>Must be a literal string.</p>",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_query_string" to VRLFunction(
        name = "parse_query_string",
        description = "Parses the <code>value</code> as a query string.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            )
        ),
        returnTypes = setOf("object")
    ),
    "parse_regex" to VRLFunction(
        name = "parse_regex",
        description = "<p>Parses the <code>value</code> using the provided <a href=\"https://en.wikipedia.org/wiki/Regular_expression\">Regex</a> <code>pattern</code>.</p>\n\n<p>This function differs from the <code>parse_regex_all</code> function in that it returns only the first match.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to search.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("regex"),
                "The regular expression pattern to search against.",
                true
            ),
            VRLFunctionArgument(
                "numeric_groups",
                setOf("boolean"),
                "If true, the index of each group in the regular expression is also captured. Index <code>0</code> contains the whole match.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_regex_all" to VRLFunction(
        name = "parse_regex_all",
        description = "<p>Parses the <code>value</code> using the provided <a href=\"https://en.wikipedia.org/wiki/Regular_expression\">Regex</a> <code>pattern</code>.</p>\n\n<p>This function differs from the <code>parse_regex</code> function in that it returns <em>all</em> matches, not just the first.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The string to search.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("regex"),
                "The regular expression pattern to search against.",
                true
            ),
            VRLFunctionArgument(
                "numeric_groups",
                setOf("boolean"),
                "If <code>true</code>, the index of each group in the regular expression is also captured. Index <code>0</code> contains the whole match.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("array", "error")
    ),
    "parse_ruby_hash" to VRLFunction(
        name = "parse_ruby_hash",
        description = "Parses the <code>value</code> as ruby hash.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string representation of the ruby hash to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_syslog" to VRLFunction(
        name = "parse_syslog",
        description = "Parses the <code>value</code> in <a href=\"https://en.wikipedia.org/wiki/Syslog\">Syslog</a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The text containing the Syslog message to parse.",
                true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_timestamp" to VRLFunction(
        name = "parse_timestamp",
        description = "Parses the <code>value</code> in <a href=\"https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers\">strptime</a> <code>format</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string", "timestamp"),
                "The text of the timestamp.",
                true
            ),
            VRLFunctionArgument(
                "format",
                setOf("string"),
                "The <a href=\"https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers\">strptime</a> format.",
                true
            ),
            VRLFunctionArgument(
                "timezone",
                setOf("string"),
                "The <a href=\"https://en.wikipedia.org/wiki/List_of_tz_database_time_zones\">TZ database</a> format. By default, this function parses the timestamp by global <a href=\"https://vector.dev/docs/reference/configuration//global-options#timezone\"><code>timezone</code> option</a>. This argument overwrites the setting and is useful for parsing timestamps without a specified timezone, such as <code>16/10/2019 12:00:00</code>.",
                false
            )
        ),
        returnTypes = setOf("timestamp", "error")
    ),
    "parse_tokens" to VRLFunction(
        name = "parse_tokens",
        description = "<p>Parses the <code>value</code> in token format. A token is considered to be one of the following:</p><ul><li>A word surrounded by whitespace.</li><li>Text delimited by double quotes: <code>\"..\"</code>. Quotes can be included in the token if they are escaped by a backslash (<code>\\</code>).</li><li>Text delimited by square brackets: <code>[..]</code>. Closing square brackets can be included in the token if they are escaped by a backslash (<code>\\</code>).</li></ul>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to tokenize.",
                true
            )
        ),
        returnTypes = setOf("array", "error")
    ),
    "parse_url" to VRLFunction(
        name = "parse_url",
        description = "Parses the <code>value</code> in <a href=\"https://en.wikipedia.org/wiki/URL\">URL</a> format.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The text of the URL.",
                true
            ),
            VRLFunctionArgument(
                "default_known_ports",
                setOf("boolean"),
                "If true and the port number is not specified in the input URL string (or matches the default port for the scheme), it is populated from well-known ports for the following schemes: <code>http</code>, <code>https</code>, <code>ws</code>, <code>wss</code>, and <code>ftp</code>.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_user_agent" to VRLFunction(
        name = "parse_user_agent",
        description = "<p>Parses the provided <code>value</code> as a user agent, which has <a href=\"https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/User-Agent\">a loosely defined format</a>.</p>\n\n<p>Parses on the basis of best effort. Returned schema depends only on the configured <code>mode</code>, so if the function fails to parse a field it will set it to <code>null</code>.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            ),
            VRLFunctionArgument(
                "mode",
                setOf("string"),
                "Determines performance and reliability characteristics.",
                false,
                defaultValue = "fast"
            )
        ),
        returnTypes = setOf("object")
    ),
    "parse_xml" to VRLFunction(
        name = "parse_xml",
        description = "Parses the <code>value</code> as XML.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string representation of the XML document to parse.",
                true
            ),
            VRLFunctionArgument(
                "trim",
                setOf("boolean"),
                "Remove excess whitespace between XML elements.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "include_attr",
                setOf("boolean"),
                "Include XML tag attributes in the returned object.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "attr_prefix",
                setOf("string"),
                "String prefix to use for XML tag attribute keys.",
                false,
                defaultValue = "@"
            ),
            VRLFunctionArgument(
                "text_key",
                setOf("string"),
                "Key name to use for expanded text nodes.",
                false,
                defaultValue = "text"
            ),
            VRLFunctionArgument(
                "always_use_text_key",
                setOf("boolean"),
                "Always return text nodes as <code>{\"&lt;text_key>\": \"value\"}.</code>",
                false,
                defaultValue = false
            ),
            VRLFunctionArgument(
                "parse_bool",
                setOf("boolean"),
                "Parse “true” and “false” as boolean.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "parse_null",
                setOf("boolean"),
                "Parse “null” as null.",
                false,
                defaultValue = true
            ),
            VRLFunctionArgument(
                "parse_number",
                setOf("boolean"),
                "Parse numbers as integers/floats.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("object", "error")
    ),
    "parse_yaml" to VRLFunction(
        name = "parse_yaml",
        description = "<p>Parses the provided <code>value</code> as YAML.</p>\n\n<p>Only YAML types are returned. If you need to convert a <code>string</code> into a <code>timestamp</code>, consider the <code>parse_timestamp</code> function.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string representation of the YAML to parse.",
                true
            )
        ),
        returnTypes = setOf("string", "integer", "float", "boolean", "object", "array", "null", "error")
    )
)
