// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val pathFunctions = mapOf(
    "del" to VRLFunction(
        name = "del",
        description = "<p>Removes the field specified by the static <code>path</code> from the target.</p>\n\n<p>For dynamic path deletion, see the <code>remove</code> function.</p>",
        isFallible = false,
        isPure = false,
        arguments = listOf(
            VRLFunctionArgument(
                "target",
                setOf("any"),
                "The path of the field to delete",
                true
            ),
            VRLFunctionArgument(
                "compact",
                setOf("boolean"),
                "After deletion, if <code>compact</code> is <code>true</code> and there is an empty object or array left, the empty object or array is also removed, cascading up to the root. This only applies to the path being deleted, and any parent paths.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("any")
    ),
    "exists" to VRLFunction(
        name = "exists",
        description = "<p>Checks whether the <code>path</code> exists for the target.</p>\n\n<p>This function distinguishes between a missing path and a path with a <code>null</code> value. A regular path lookup, such as <code>.foo</code>, cannot distinguish between the two cases since it always returns <code>null</code> if the path doesn’t exist.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "field",
                setOf("any"),
                "The path of the field to check.",
                true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "get" to VRLFunction(
        name = "get",
        description = "<p>Dynamically get the value of a given path.</p>\n\n<p>If you know the path you want to look up, use static paths such as <code>.foo.bar[1]</code> to get the value of that path. However, if you do not know the path names, use the dynamic <code>get</code> function to get the requested value.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to query.",
                true
            ),
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "An array of path segments to look for the value.",
                true
            )
        ),
        returnTypes = setOf("any", "error")
    ),
    "remove" to VRLFunction(
        name = "remove",
        description = "<p>Dynamically remove the value for a given path.</p>\n\n<p>If you know the path you want to remove, use the <code>del</code> function and static paths such as <code>del(.foo.bar[1])</code> to remove the value at that path. The <code>del</code> function returns the deleted value, and is more performant than <code>remove</code>. However, if you do not know the path names, use the dynamic <code>remove</code> function to remove the value at the provided path.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to remove data from.",
                true
            ),
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "An array of path segments to remove the value from.",
                true
            ),
            VRLFunctionArgument(
                "compact",
                setOf("boolean"),
                "After deletion, if <code>compact</code> is <code>true</code>, any empty objects or arrays left are also removed.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "array", "error")
    ),
    "set" to VRLFunction(
        name = "set",
        description = "<p>Dynamically insert data into the path of a given object or array.</p>\n\n<p>If you know the path you want to assign a value to, use static path assignments such as <code>.foo.bar[1] = true</code> for improved performance and readability. However, if you do not know the path names, use the dynamic <code>set</code> function to insert the data into the object or array.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to insert data into.",
                true
            ),
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "An array of path segments to insert the value into.",
                true
            ),
            VRLFunctionArgument(
                "data",
                setOf("any"),
                "The data to be inserted.",
                true
            )
        ),
        returnTypes = setOf("object", "array", "error")
    )
)
