// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val pathFunctions = mapOf(
    "del" to VRLFunction(
        name = "del",
        description = "<p>Removes the field specified by the static <code>path</code> from the target.</p>\n\n<p>For dynamic path deletion, see the <code>remove</code> function.</p>",
        isFallible = false,
        isPure = false,
        arguments = listOf(
            VRLFunctionArgument(
                "target",
                setOf("any"),
                "The path of the field to delete",
                true
            ),
            VRLFunctionArgument(
                "compact",
                setOf("boolean"),
                "After deletion, if <code>compact</code> is <code>true</code> and there is an empty object or array left, the empty object or array is also removed, cascading up to the root. This only applies to the path being deleted, and any parent paths.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("any"),
        examples = listOf(
            VRLFunctionExample(
                "Delete a field",
                ". = { \"foo\": \"bar\" }\ndel(.foo)",
                "bar",
                false
            ),
            VRLFunctionExample(
                "Rename a field",
                ". = { \"old\": \"foo\" }\n.new = del(.old)\n.",
                "{\n  \"new\": \"foo\"\n}",
                false
            ),
            VRLFunctionExample(
                "Returns null for unknown field",
                "del({\"foo\": \"bar\"}.baz)",
                "",
                false
            ),
            VRLFunctionExample(
                "External target",
                ". = { \"foo\": true, \"bar\": 10 }\ndel(.foo)\n.",
                "{\n  \"bar\": 10\n}",
                false
            ),
            VRLFunctionExample(
                "Delete field from variable",
                "var = { \"foo\": true, \"bar\": 10 }\ndel(var.foo)\nvar",
                "{\n  \"bar\": 10\n}",
                false
            ),
            VRLFunctionExample(
                "Delete object field",
                "var = { \"foo\": {\"nested\": true}, \"bar\": 10 }\ndel(var.foo.nested, false)\nvar",
                "{\n  \"bar\": 10,\n  \"foo\": {}\n}",
                false
            ),
            VRLFunctionExample(
                "Compact object field",
                "var = { \"foo\": {\"nested\": true}, \"bar\": 10 }\ndel(var.foo.nested, true)\nvar",
                "{\n  \"bar\": 10\n}",
                false
            )
        )
    ),
    "exists" to VRLFunction(
        name = "exists",
        description = "<p>Checks whether the <code>path</code> exists for the target.</p>\n\n<p>This function distinguishes between a missing path and a path with a <code>null</code> value. A regular path lookup, such as <code>.foo</code>, cannot distinguish between the two cases since it always returns <code>null</code> if the path doesn’t exist.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "field",
                setOf("any"),
                "The path of the field to check.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Exists (field)",
                ". = { \"field\": 1 }\nexists(.field)",
                "true",
                false
            ),
            VRLFunctionExample(
                "Exists (array element)",
                ". = { \"array\": [1, 2, 3] }\nexists(.array[2])",
                "true",
                false
            ),
            VRLFunctionExample(
                "Does not exist (field)",
                "exists({ \"foo\": \"bar\"}.baz)",
                "false",
                false
            )
        )
    ),
    "get" to VRLFunction(
        name = "get",
        description = "<p>Dynamically get the value of a given path.</p>\n\n<p>If you know the path you want to look up, use static paths such as <code>.foo.bar[1]</code> to get the value of that path. However, if you do not know the path names, use the dynamic <code>get</code> function to get the requested value.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to query.",
                true
            ),
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "An array of path segments to look for the value.",
                true
            )
        ),
        returnTypes = setOf("any", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Single-segment top-level field",
                "get!(value: {\"foo\": \"bar\"}, path: [\"foo\"])",
                "bar",
                false
            ),
            VRLFunctionExample(
                "Returns null for unknown field",
                "get!(value: {\"foo\": \"bar\"}, path: [\"baz\"])",
                "",
                false
            ),
            VRLFunctionExample(
                "Multi-segment nested field",
                "get!(value: {\"foo\": { \"bar\": true }}, path: [\"foo\", \"bar\"])",
                "true",
                false
            ),
            VRLFunctionExample(
                "Array indexing",
                "get!(value: [92, 42], path: [0])",
                "92",
                false
            ),
            VRLFunctionExample(
                "Array indexing (negative)",
                "get!(value: [\"foo\", \"bar\", \"baz\"], path: [-2])",
                "bar",
                false
            ),
            VRLFunctionExample(
                "Nested indexing",
                "get!(value: {\"foo\": { \"bar\": [92, 42] }}, path: [\"foo\", \"bar\", 1])",
                "42",
                false
            ),
            VRLFunctionExample(
                "External target",
                "get!(value: ., path: [\"foo\"])",
                "true",
                false
            ),
            VRLFunctionExample(
                "Variable",
                "var = { \"foo\": true }\nget!(value: var, path: [\"foo\"])",
                "true",
                false
            ),
            VRLFunctionExample(
                "Missing index",
                "get!(value: {\"foo\": { \"bar\": [92, 42] }}, path: [\"foo\", \"bar\", 1, -1])",
                "",
                false
            ),
            VRLFunctionExample(
                "Invalid indexing",
                "get!(value: [42], path: [\"foo\"])",
                "",
                false
            ),
            VRLFunctionExample(
                "Invalid segment type",
                "get!(value: {\"foo\": { \"bar\": [92, 42] }}, path: [\"foo\", true])",
                "function call error for \"get\" at (0:62): path segment must be either string or integer, not boolean",
                true
            )
        )
    ),
    "remove" to VRLFunction(
        name = "remove",
        description = "<p>Dynamically remove the value for a given path.</p>\n\n<p>If you know the path you want to remove, use the <code>del</code> function and static paths such as <code>del(.foo.bar[1])</code> to remove the value at that path. The <code>del</code> function returns the deleted value, and is more performant than <code>remove</code>. However, if you do not know the path names, use the dynamic <code>remove</code> function to remove the value at the provided path.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to remove data from.",
                true
            ),
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "An array of path segments to remove the value from.",
                true
            ),
            VRLFunctionArgument(
                "compact",
                setOf("boolean"),
                "After deletion, if <code>compact</code> is <code>true</code>, any empty objects or arrays left are also removed.",
                false,
                defaultValue = false
            )
        ),
        returnTypes = setOf("object", "array", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Single-segment top-level field",
                "remove!(value: { \"foo\": \"bar\" }, path: [\"foo\"])",
                "{}",
                false
            ),
            VRLFunctionExample(
                "Remove unknown field",
                "remove!(value: {\"foo\": \"bar\"}, path: [\"baz\"])",
                "{\n  \"foo\": \"bar\"\n}",
                false
            ),
            VRLFunctionExample(
                "Multi-segment nested field",
                "remove!(value: { \"foo\": { \"bar\": \"baz\" } }, path: [\"foo\", \"bar\"])",
                "{\n  \"foo\": {}\n}",
                false
            ),
            VRLFunctionExample(
                "Array indexing",
                "remove!(value: [\"foo\", \"bar\", \"baz\"], path: [-2])",
                "[\"foo\",\"baz\"]",
                false
            ),
            VRLFunctionExample(
                "Compaction",
                "remove!(value: { \"foo\": { \"bar\": [42], \"baz\": true } }, path: [\"foo\", \"bar\", 0], compact: true)",
                "{\n  \"foo\": {\n    \"baz\": true\n  }\n}",
                false
            ),
            VRLFunctionExample(
                "Compact object",
                "remove!(value: {\"foo\": { \"bar\": true }}, path: [\"foo\", \"bar\"], compact: true)",
                "{}",
                false
            ),
            VRLFunctionExample(
                "Compact array",
                "remove!(value: {\"foo\": [42], \"bar\": true }, path: [\"foo\", 0], compact: true)",
                "{\n  \"bar\": true\n}",
                false
            ),
            VRLFunctionExample(
                "External target",
                "remove!(value: ., path: [\"foo\"])",
                "{}",
                false
            ),
            VRLFunctionExample(
                "Variable",
                "var = { \"foo\": true }\nremove!(value: var, path: [\"foo\"])",
                "{}",
                false
            ),
            VRLFunctionExample(
                "Missing index",
                "remove!(value: {\"foo\": { \"bar\": [92, 42] }}, path: [\"foo\", \"bar\", 1, -1])",
                "{\n  \"foo\": {\n    \"bar\": [\n      92,\n      42\n    ]\n  }\n}",
                false
            ),
            VRLFunctionExample(
                "Invalid indexing",
                "remove!(value: [42], path: [\"foo\"])",
                "[42]",
                false
            ),
            VRLFunctionExample(
                "Invalid segment type",
                "remove!(value: {\"foo\": { \"bar\": [92, 42] }}, path: [\"foo\", true])",
                "function call error for \"remove\" at (0:65): path segment must be either string or integer, not boolean",
                true
            )
        )
    ),
    "set" to VRLFunction(
        name = "set",
        description = "<p>Dynamically insert data into the path of a given object or array.</p>\n\n<p>If you know the path you want to assign a value to, use static path assignments such as <code>.foo.bar[1] = true</code> for improved performance and readability. However, if you do not know the path names, use the dynamic <code>set</code> function to insert the data into the object or array.</p>",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("object", "array"),
                "The object or array to insert data into.",
                true
            ),
            VRLFunctionArgument(
                "path",
                setOf("array"),
                "An array of path segments to insert the value into.",
                true
            ),
            VRLFunctionArgument(
                "data",
                setOf("any"),
                "The data to be inserted.",
                true
            )
        ),
        returnTypes = setOf("object", "array", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Single-segment top-level field",
                "set!(value: { \"foo\": \"bar\" }, path: [\"foo\"], data: \"baz\")",
                "{\n  \"foo\": \"baz\"\n}",
                false
            ),
            VRLFunctionExample(
                "Multi-segment nested field",
                "set!(value: { \"foo\": { \"bar\": \"baz\" } }, path: [\"foo\", \"bar\"], data: \"qux\")",
                "{\n  \"foo\": {\n    \"bar\": \"qux\"\n  }\n}",
                false
            ),
            VRLFunctionExample(
                "Array",
                "set!(value: [\"foo\", \"bar\", \"baz\"], path: [-2], data: 42)",
                "[\"foo\",42,\"baz\"]",
                false
            ),
            VRLFunctionExample(
                "Nested fields",
                "set!(value: {}, path: [\"foo\", \"bar\"], data: \"baz\")",
                "{\n  \"foo\": {\n    \"bar\": \"baz\"\n  }\n}",
                false
            ),
            VRLFunctionExample(
                "Nested indexing",
                "set!(value: {\"foo\": { \"bar\": [] }}, path: [\"foo\", \"bar\", 1], data: \"baz\")",
                "{\n  \"foo\": {\n    \"bar\": [\n      null,\n      \"baz\"\n    ]\n  }\n}",
                false
            ),
            VRLFunctionExample(
                "External target",
                "set!(value: ., path: [\"bar\"], data: \"baz\")",
                "{\n  \"bar\": \"baz\",\n  \"foo\": true\n}",
                false
            ),
            VRLFunctionExample(
                "Variable",
                "var = { \"foo\": true }\nset!(value: var, path: [\"bar\"], data: \"baz\")",
                "{\n  \"bar\": \"baz\",\n  \"foo\": true\n}",
                false
            ),
            VRLFunctionExample(
                "Invalid indexing",
                "set!(value: [], path: [\"foo\"], data: \"baz\")",
                "{\n  \"foo\": \"baz\"\n}",
                false
            ),
            VRLFunctionExample(
                "Invalid segment type",
                "set!({\"foo\": { \"bar\": [92, 42] }}, [\"foo\", true], \"baz\")",
                "function call error for \"set\" at (0:56): path segment must be either string or integer, not boolean",
                true
            )
        )
    )
)
