// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val randomFunctions = mapOf(
    "random_bool" to VRLFunction(
        name = "random_bool",
        description = "Returns a random boolean.",
        isFallible = false,
        isPure = true,
        arguments = listOf(),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Random boolean",
                "is_boolean(random_bool())",
                "true",
                false
            )
        )
    ),
    "random_bytes" to VRLFunction(
        name = "random_bytes",
        description = "A cryptographically secure random number generator. Returns a string value containing the number of random bytes requested.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "length",
                setOf("integer"),
                "The number of bytes to generate. Must not be larger than 64k.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Generate random base 64 encoded bytes",
                "encode_base64(random_bytes(16))",
                "LNu0BBgUbh7XAlXbjSOomQ==",
                false
            ),
            VRLFunctionExample(
                "Generate 16 random bytes",
                "length(random_bytes(16))",
                "16",
                false
            )
        )
    ),
    "random_float" to VRLFunction(
        name = "random_float",
        description = "Returns a random float between [min, max).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "min",
                setOf("float"),
                "Minimum value (inclusive).",
                true
            ),
            VRLFunctionArgument(
                "max",
                setOf("float"),
                "Maximum value (exclusive).",
                true
            )
        ),
        returnTypes = setOf("float", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Random float from 0.0 to 10.0, not including 10.0",
                "f = random_float(0.0, 10.0)\nf >= 0 && f < 10",
                "true",
                false
            )
        )
    ),
    "random_int" to VRLFunction(
        name = "random_int",
        description = "Returns a random integer between [min, max).",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "min",
                setOf("integer"),
                "Minimum value (inclusive).",
                true
            ),
            VRLFunctionArgument(
                "max",
                setOf("integer"),
                "Maximum value (exclusive).",
                true
            )
        ),
        returnTypes = setOf("integer", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Random integer from 0 to 10, not including 10",
                "i = random_int(0, 10)\ni >= 0 && i < 10",
                "true",
                false
            )
        )
    ),
    "uuid_from_friendly_id" to VRLFunction(
        name = "uuid_from_friendly_id",
        description = "Convert a Friendly ID (base62 encoding a 128-bit word) to a UUID.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "A string that is a Friendly ID",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Convert a Friendly ID to a UUID",
                "uuid_from_friendly_id!(\"3s87yEvnmkiPBMHsj8bwwc\")",
                "7f41deed-d5e2-8b5e-7a13-ab4ff93cfad2",
                false
            )
        )
    ),
    "uuid_v4" to VRLFunction(
        name = "uuid_v4",
        description = "Generates a random <a href=\"https://en.wikipedia.org/wiki/Universally_unique_identifier#Version_4_%28random%29\">UUIDv4</a> string.",
        isFallible = false,
        isPure = true,
        arguments = listOf(),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Create a UUIDv4",
                "uuid_v4()",
                "1d262f4f-199b-458d-879f-05fd0a5f0683",
                false
            )
        )
    ),
    "uuid_v7" to VRLFunction(
        name = "uuid_v7",
        description = "Generates a random <a href=\"https://datatracker.ietf.org/doc/html/draft-peabody-dispatch-new-uuid-format-04#name-uuid-version-7\">UUIDv7</a> string.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "timestamp",
                setOf("timestamp"),
                "The timestamp used to generate the UUIDv7.",
                false,
                defaultValue = "`now()`"
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Create a UUIDv7 with implicit now()",
                "uuid_v7()",
                "0135ddb4-a444-794c-a7a2-088f260104c0",
                false
            ),
            VRLFunctionExample(
                "Create a UUIDv7 with explicit now()",
                "uuid_v7(now())",
                "0135ddb4-a444-794c-a7a2-088f260104c0",
                false
            ),
            VRLFunctionExample(
                "Create a UUIDv7 with custom timestamp",
                "uuid_v7(t'2020-12-30T22:20:53.824727Z')",
                "0176b5bd-5d19-794c-a7a2-088f260104c0",
                false
            )
        )
    )
)
