// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val stringFunctions = mapOf(
    "basename" to VRLFunction(
        name = "basename",
        description = "Returns the filename component of the given <code>path</code>. This is similar to the Unix <code>basename</code> command. If the path ends in a directory separator, the function returns the name of the directory.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The path from which to extract the basename.",
                true
            )
        ),
        returnTypes = setOf("string", "null", "error")
    ),
    "camelcase" to VRLFunction(
        name = "camelcase",
        description = "Takes the <code>value</code> string, and turns it into camelCase. Optionally, you can pass in the existing case of the function, or else an attempt is made to determine the case automatically.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to camelCase.",
                true
            ),
            VRLFunctionArgument(
                "original_case",
                setOf("string"),
                "Optional hint on the original case type. Must be one of: kebab-case, camelCase, PascalCase, SCREAMING_SNAKE, snake_case",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "community_id" to VRLFunction(
        name = "community_id",
        description = "Generates an ID based on the <a href=\"https://github.com/corelight/community-id-spec\">Community ID Spec</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "source_ip",
                setOf("string"),
                "The source IP address.",
                true
            ),
            VRLFunctionArgument(
                "destination_ip",
                setOf("string"),
                "The destination IP address.",
                true
            ),
            VRLFunctionArgument(
                "protocol",
                setOf("integer"),
                "The protocol number.",
                true
            ),
            VRLFunctionArgument(
                "source_port",
                setOf("integer"),
                "The source port or ICMP type.",
                false
            ),
            VRLFunctionArgument(
                "destination_port",
                setOf("integer"),
                "The destination port or ICMP code.",
                false
            ),
            VRLFunctionArgument(
                "seed",
                setOf("integer"),
                "The custom seed number.",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "contains" to VRLFunction(
        name = "contains",
        description = "Determines whether the <code>value</code> string contains the specified <code>substring</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The text to search.",
                true
            ),
            VRLFunctionArgument(
                "substring",
                setOf("string"),
                "The substring to search for in <code>value</code>.",
                true
            ),
            VRLFunctionArgument(
                "case_sensitive",
                setOf("boolean"),
                "Whether the match should be case sensitive.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "contains_all" to VRLFunction(
        name = "contains_all",
        description = "Determines whether the <code>value</code> string contains all the specified <code>substrings</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The text to search.",
                true
            ),
            VRLFunctionArgument(
                "substrings",
                setOf("array"),
                "An array of substrings to search for in <code>value</code>.",
                true
            ),
            VRLFunctionArgument(
                "case_sensitive",
                setOf("boolean"),
                "Whether the match should be case sensitive.",
                false
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "dirname" to VRLFunction(
        name = "dirname",
        description = "Returns the directory component of the given <code>path</code>. This is similar to the Unix <code>dirname</code> command. The directory component is the path with the final component removed.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The path from which to extract the directory name.",
                true
            )
        ),
        returnTypes = setOf("string", "error")
    ),
    "downcase" to VRLFunction(
        name = "downcase",
        description = "Downcases the <code>value</code> string, where downcase is defined according to the Unicode Derived Core Property Lowercase.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to lowercase.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "ends_with" to VRLFunction(
        name = "ends_with",
        description = "Determines whether the <code>value</code> string ends with the specified <code>substring</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to search.",
                true
            ),
            VRLFunctionArgument(
                "substring",
                setOf("string"),
                "The substring with which <code>value</code> must end.",
                true
            ),
            VRLFunctionArgument(
                "case_sensitive",
                setOf("boolean"),
                "Whether the match should be case sensitive.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "find" to VRLFunction(
        name = "find",
        description = "Determines from left to right the start position of the first found element in <code>value</code> that matches <code>pattern</code>. Returns null if not found.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to find the pattern in.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("string", "regex"),
                "The regular expression or string pattern to match against.",
                true
            ),
            VRLFunctionArgument(
                "from",
                setOf("integer"),
                "Offset to start searching.",
                false,
                defaultValue = 0
            )
        ),
        returnTypes = setOf("integer", "null")
    ),
    "join" to VRLFunction(
        name = "join",
        description = "Joins each string in the <code>value</code> array into a single string, with items optionally separated from one another by a <code>separator</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("array"),
                "The array of strings to join together.",
                true
            ),
            VRLFunctionArgument(
                "separator",
                setOf("string"),
                "The string separating each original element when joined.",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "kebabcase" to VRLFunction(
        name = "kebabcase",
        description = "Takes the <code>value</code> string, and turns it into kebab-case. Optionally, you can pass in the existing case of the function, or else we will try to figure out the case automatically.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to kebab-case.",
                true
            ),
            VRLFunctionArgument(
                "original_case",
                setOf("string"),
                "Optional hint on the original case type. Must be one of: kebab-case, camelCase, PascalCase, SCREAMING_SNAKE, snake_case",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "match" to VRLFunction(
        name = "match",
        description = "Determines whether the <code>value</code> matches the <code>pattern</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The value to match.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("regex"),
                "The regular expression pattern to match against.",
                true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "match_any" to VRLFunction(
        name = "match_any",
        description = "Determines whether <code>value</code> matches any of the given <code>patterns</code>. All patterns are checked in a single pass over the target string, giving this function a potential performance advantage over the multiple calls in the <code>match</code> function.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The value to match.",
                true
            ),
            VRLFunctionArgument(
                "patterns",
                setOf("array"),
                "The array of regular expression patterns to match against.",
                true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "parse_float" to VRLFunction(
        name = "parse_float",
        description = "Parses the string <code>value</code> representing a floating point number in base 10 to a float.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to parse.",
                true
            )
        ),
        returnTypes = setOf("float", "error")
    ),
    "pascalcase" to VRLFunction(
        name = "pascalcase",
        description = "Takes the <code>value</code> string, and turns it into PascalCase. Optionally, you can pass in the existing case of the function, or else we will try to figure out the case automatically.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to PascalCase.",
                true
            ),
            VRLFunctionArgument(
                "original_case",
                setOf("string"),
                "Optional hint on the original case type. Must be one of: kebab-case, camelCase, PascalCase, SCREAMING_SNAKE, snake_case",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "redact" to VRLFunction(
        name = "redact",
        description = "<p>Redact sensitive data in <code>value</code> such as:</p><ul><li><a href=\"https://www.ssa.gov/history/ssn/geocard.html\">US social security card numbers</a></li><li>Other forms of personally identifiable information with custom patterns</li></ul><p>This can help achieve compliance by ensuring sensitive data does not leave your network.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string", "object", "array"),
                "<p>The value to redact sensitive data from.</p><p>The function’s behavior depends on <code>value</code>’s type:</p><ul><li>For strings, the sensitive data is redacted and a new string is returned.</li><li>For arrays, the sensitive data is redacted in each string element.</li><li>For objects, the sensitive data in each string value is masked, but the keys are not masked.</li></ul><p>For arrays and objects, the function recurses into any nested arrays or objects. Any non-string elements are skipped.</p><p>Redacted text is replaced with <code>[REDACTED]</code>.</p>",
                true
            ),
            VRLFunctionArgument(
                "filters",
                setOf("array"),
                "<p>List of filters applied to <code>value</code>.</p><p>Each filter can be specified in the following ways:</p><ul><li>As a regular expression, which is used to redact text that match it.</li><li>As an object with a <code>type</code> key that corresponds to a named filter and additional keys for customizing that filter.</li><li>As a named filter, if it has no required parameters.</li></ul><p>Named filters can be a:</p><ul><li><code>pattern</code>: Redacts text matching any regular expressions specified in the <code>patterns</code> key, which is required. This is the expanded version of just passing a regular expression as a filter.</li><li><code>us_social_security_number</code>: Redacts US social security card numbers.</li></ul><p>See examples for more details.</p><p>This parameter must be a static expression so that the argument can be validated at compile-time to avoid runtime errors. You cannot use variables or other dynamic expressions with it.</p>",
                true
            ),
            VRLFunctionArgument(
                "redactor",
                setOf("string", "object"),
                "<p>Specifies what to replace the redacted strings with.</p><p>It is given as an object with a “type” key specifying the type of redactor to use and additional keys depending on the type. The following types are supported:</p><ul><li><code>full</code>: The default. Replace with the string “[REDACTED]”.</li><li><code>text</code>: Replace with a custom string. The <code>replacement</code> key is required, and must contain the string that is used as a replacement.</li><li><code>sha2</code>: Hash the redacted text with SHA-2 as with <a href=\"https://en.wikipedia.org/wiki/SHA-2\"><code>sha2</code></a>. Supports two optional parameters:<ul><li><code>variant</code>: The variant of the algorithm to use. Defaults to SHA-512/256.</li><li><code>encoding</code>: How to encode the hash as text. Can be base16 or base64. Defaults to base64.</li></ul></li><li><code>sha3</code>: Hash the redacted text with SHA-3 as with <a href=\"https://en.wikipedia.org/wiki/SHA-3\"><code>sha3</code></a>. Supports two optional parameters:<ul><li><code>variant</code>: The variant of the algorithm to use. Defaults to SHA3-512.</li><li><code>encoding</code>: How to encode the hash as text. Can be base16 or base64. Defaults to base64.</li></ul></li></ul><p>As a convenience you can use a string as a shorthand for common redactor patterns:</p><ul><li><code>\"full\"</code> is equivalent to <code>{\"type\": \"full\"}</code></li><li><code>\"sha2\"</code> is equivalent to <code>{\"type\": \"sha2\", \"variant\": \"SHA-512/256\", \"encoding\": \"base64\"}</code></li><li><code>\"sha3\"</code> is equivalent to <code>{\"type\": \"sha3\", \"variant\": \"SHA3-512\", \"encoding\": \"base64\"}</code></li></ul><p>This parameter must be a static expression so that the argument can be validated at compile-time to avoid runtime errors. You cannot use variables or other dynamic expressions with it.</p>",
                false
            )
        ),
        returnTypes = setOf("string", "object", "array")
    ),
    "replace" to VRLFunction(
        name = "replace",
        description = "<p>Replaces all matching instances of <code>pattern</code> in <code>value</code>.</p>\n\n<p>The <code>pattern</code> argument accepts regular expression capture groups.</p>\n\n<p><strong>Note when using capture groups</strong>:</p><ul><li>You will need to escape the <code>\$</code> by using <code>\$\$</code> to avoid Vector interpreting it as an <a href=\"https://vector.dev/docs/reference/environment_variables/#escaping\">environment variable when loading configuration</a></li><li>If you want a literal <code>\$</code> in the replacement pattern, you will also need to escape this with <code>\$\$</code>. When combined with environment variable interpolation in config files this means you will need to use <code>\$\$\$\$</code> to have a literal <code>\$</code> in the replacement pattern.</li></ul>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The original string.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("string", "regex"),
                "Replace all matches of this pattern. Can be a static string or a regular expression.",
                true
            ),
            VRLFunctionArgument(
                "with",
                setOf("string"),
                "The string that the matches are replaced with.",
                true
            ),
            VRLFunctionArgument(
                "count",
                setOf("integer"),
                "The maximum number of replacements to perform. <code>-1</code> means replace all matches.",
                false,
                defaultValue = -1
            )
        ),
        returnTypes = setOf("string")
    ),
    "replace_with" to VRLFunction(
        name = "replace_with",
        description = "<p>Replaces all matching instances of <code>pattern</code> using a closure.</p>\n\n<p>The <code>pattern</code> argument accepts a regular expression that can use capture groups.</p>\n\n<p>The function uses the function closure syntax to compute the replacement values.</p>\n\n<p>The closure takes a single parameter, which is an array, where the first item is always present and contains the entire string that matched <code>pattern</code>. The items from index one on contain the capture groups of the corresponding index. If a capture group is optional, the value may be null if it didn’t match.</p>\n\n<p>The value returned by the closure must be a string and will replace the section of the input that was matched.</p>\n\n<p>This returns a new string with the replacements, the original string is not mutated.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The original string.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("regex"),
                "Replace all matches of this pattern. Must be a regular expression.",
                true
            ),
            VRLFunctionArgument(
                "count",
                setOf("integer"),
                "The maximum number of replacements to perform. <code>-1</code> means replace all matches.",
                false,
                defaultValue = -1
            )
        ),
        returnTypes = setOf("string")
    ),
    "screamingsnakecase" to VRLFunction(
        name = "screamingsnakecase",
        description = "Takes the <code>value</code> string, and turns it into SCREAMING_SNAKE case. Optionally, you can pass in the existing case of the function, or else we will try to figure out the case automatically.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to SCREAMING_SNAKE case.",
                true
            ),
            VRLFunctionArgument(
                "original_case",
                setOf("string"),
                "Optional hint on the original case type. Must be one of: kebab-case, camelCase, PascalCase, SCREAMING_SNAKE, snake_case",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "shannon_entropy" to VRLFunction(
        name = "shannon_entropy",
        description = "Generates <a href=\"https://en.wikipedia.org/wiki/Entropy_%28information_theory%29\">Shannon entropy</a> from given string. It can generate it based on string bytes, codepoints, or graphemes.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The input string.",
                true
            ),
            VRLFunctionArgument(
                "segmentation",
                setOf("string"),
                "<p>Defines how to split the string to calculate entropy, based on occurrences of segments.</p><p>Byte segmentation is the fastest, but it might give undesired results when handling UTF-8 strings, while grapheme segmentation is the slowest, but most correct in these cases.</p>",
                false,
                defaultValue = "byte"
            )
        ),
        returnTypes = setOf("float")
    ),
    "sieve" to VRLFunction(
        name = "sieve",
        description = "<p>Keeps only matches of <code>pattern</code> in <code>value</code>.</p>\n\n<p>This can be used to define patterns that are allowed in the string and remove everything else.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The original string.",
                true
            ),
            VRLFunctionArgument(
                "permitted_characters",
                setOf("regex"),
                "Keep all matches of this pattern.",
                true
            ),
            VRLFunctionArgument(
                "replace_single",
                setOf("string"),
                "The string to use to replace single rejected characters.",
                false
            ),
            VRLFunctionArgument(
                "replace_repeated",
                setOf("string"),
                "The string to use to replace multiple sequential instances of rejected characters.",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "slice" to VRLFunction(
        name = "slice",
        description = "<p>Returns a slice of <code>value</code> between the <code>start</code> and <code>end</code> positions.</p>\n\n<p>If the <code>start</code> and <code>end</code> parameters are negative, they refer to positions counting from the right of the string or array. If <code>end</code> refers to a position that is greater than the length of the string or array, a slice up to the end of the string or array is returned.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string", "array"),
                "The string or array to slice.",
                true
            ),
            VRLFunctionArgument(
                "start",
                setOf("integer"),
                "The inclusive start position. A zero-based index that can be negative.",
                true
            ),
            VRLFunctionArgument(
                "end",
                setOf("integer"),
                "The exclusive end position. A zero-based index that can be negative.",
                false,
                defaultValue = "String length"
            )
        ),
        returnTypes = setOf("string", "array")
    ),
    "snakecase" to VRLFunction(
        name = "snakecase",
        description = "Takes the <code>value</code> string, and turns it into snake_case. Optionally, you can pass in the existing case of the function, or else we will try to figure out the case automatically.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to snake_case.",
                true
            ),
            VRLFunctionArgument(
                "original_case",
                setOf("string"),
                "Optional hint on the original case type. Must be one of: kebab-case, camelCase, PascalCase, SCREAMING_SNAKE, snake_case",
                false
            ),
            VRLFunctionArgument(
                "excluded_boundaries",
                setOf("array"),
                "Case boundaries to exclude during conversion.",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "split" to VRLFunction(
        name = "split",
        description = "Splits the <code>value</code> string using <code>pattern</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to split.",
                true
            ),
            VRLFunctionArgument(
                "pattern",
                setOf("string", "regex"),
                "The string is split whenever this pattern is matched.",
                true
            ),
            VRLFunctionArgument(
                "limit",
                setOf("integer"),
                "The maximum number of substrings to return.",
                false
            )
        ),
        returnTypes = setOf("array")
    ),
    "split_path" to VRLFunction(
        name = "split_path",
        description = "Splits the given <code>path</code> into its constituent components, returning an array of strings. Each component represents a part of the file system path hierarchy.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The path to split into components.",
                true
            )
        ),
        returnTypes = setOf("array", "error")
    ),
    "starts_with" to VRLFunction(
        name = "starts_with",
        description = "Determines whether <code>value</code> begins with <code>substring</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to search.",
                true
            ),
            VRLFunctionArgument(
                "substring",
                setOf("string"),
                "The substring that the <code>value</code> must start with.",
                true
            ),
            VRLFunctionArgument(
                "case_sensitive",
                setOf("boolean"),
                "Whether the match should be case sensitive.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("boolean")
    ),
    "strip_ansi_escape_codes" to VRLFunction(
        name = "strip_ansi_escape_codes",
        description = "Strips <a href=\"https://en.wikipedia.org/wiki/ANSI_escape_code\">ANSI escape codes</a> from <code>value</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to strip.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "strip_whitespace" to VRLFunction(
        name = "strip_whitespace",
        description = "Strips whitespace from the start and end of <code>value</code>, where whitespace is defined by the <a href=\"https://en.wikipedia.org/wiki/Unicode_character_property#Whitespace\">Unicode <code>White_Space</code> property</a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to trim.",
                true
            )
        ),
        returnTypes = setOf("string")
    ),
    "truncate" to VRLFunction(
        name = "truncate",
        description = "Truncates the <code>value</code> string up to the <code>limit</code> number of characters.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to truncate.",
                true
            ),
            VRLFunctionArgument(
                "limit",
                setOf("integer"),
                "The number of characters to truncate the string after.",
                true
            ),
            VRLFunctionArgument(
                "suffix",
                setOf("string"),
                "A custom suffix to be appended to truncated strings. If a custom <code>suffix</code> is provided, the total length of the string will be <code>limit + &lt;suffix length></code>.",
                false
            )
        ),
        returnTypes = setOf("string")
    ),
    "upcase" to VRLFunction(
        name = "upcase",
        description = "Upcases <code>value</code>, where upcase is defined according to the Unicode Derived Core Property Uppercase.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The string to convert to uppercase.",
                true
            )
        ),
        returnTypes = setOf("string")
    )
)
