// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val systemFunctions = mapOf(
    "dns_lookup" to VRLFunction(
        name = "dns_lookup",
        description = "Performs a DNS lookup on the provided domain name.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The domain name to query.",
                true
            ),
            VRLFunctionArgument(
                "qtype",
                setOf("string"),
                "The DNS record type to query (e.g., A, AAAA, MX, TXT). Defaults to A.",
                false,
                defaultValue = "A"
            ),
            VRLFunctionArgument(
                "class",
                setOf("string"),
                "The DNS query class. Defaults to IN (Internet).",
                false,
                defaultValue = "IN"
            ),
            VRLFunctionArgument(
                "options",
                setOf("object"),
                "DNS resolver options. Supported fields: servers (array of nameserver addresses), timeout (seconds), attempts (number of retry attempts), ndots, aa_only, tcp, recurse, rotate.",
                false,
                defaultValue = "{ }"
            )
        ),
        returnTypes = setOf("object"),
        examples = listOf(
            VRLFunctionExample(
                "Basic lookup",
                "res = dns_lookup!(\"dns.google\")\n# reset non-static ttl so result is static\nres.answers = map_values(res.answers) -> |value| {\n  value.ttl = 600\n  value\n}\n# remove extra responses for example\nres.answers = filter(res.answers) -> |_, value| {\n    value.rData == \"8.8.8.8\"\n}\n# remove class since this is also dynamic\nres.additional = map_values(res.additional) -> |value| {\n    del(value.class)\n    value\n}\nres",
                "{\n  \"additional\": [\n    {\n      \"domainName\": \"\",\n      \"rData\": \"OPT ...\",\n      \"recordType\": \"OPT\",\n      \"recordTypeId\": 41,\n      \"ttl\": 0\n    }\n  ],\n  \"answers\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"rData\": \"8.8.8.8\",\n      \"recordType\": \"A\",\n      \"recordTypeId\": 1,\n      \"ttl\": 600\n    }\n  ],\n  \"authority\": [],\n  \"fullRcode\": 0,\n  \"header\": {\n    \"aa\": false,\n    \"ad\": false,\n    \"anCount\": 2,\n    \"arCount\": 1,\n    \"cd\": false,\n    \"nsCount\": 0,\n    \"opcode\": 0,\n    \"qdCount\": 1,\n    \"qr\": true,\n    \"ra\": true,\n    \"rcode\": 0,\n    \"rd\": true,\n    \"tc\": false\n  },\n  \"question\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"questionType\": \"A\",\n      \"questionTypeId\": 1\n    }\n  ],\n  \"rcodeName\": \"NOERROR\"\n}",
                false
            ),
            VRLFunctionExample(
                "Custom class and qtype",
                "res = dns_lookup!(\"dns.google\", class: \"IN\", qtype: \"A\")\n# reset non-static ttl so result is static\nres.answers = map_values(res.answers) -> |value| {\n  value.ttl = 600\n  value\n}\n# remove extra responses for example\nres.answers = filter(res.answers) -> |_, value| {\n    value.rData == \"8.8.8.8\"\n}\n# remove class since this is also dynamic\nres.additional = map_values(res.additional) -> |value| {\n    del(value.class)\n    value\n}\nres",
                "{\n  \"additional\": [\n    {\n      \"domainName\": \"\",\n      \"rData\": \"OPT ...\",\n      \"recordType\": \"OPT\",\n      \"recordTypeId\": 41,\n      \"ttl\": 0\n    }\n  ],\n  \"answers\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"rData\": \"8.8.8.8\",\n      \"recordType\": \"A\",\n      \"recordTypeId\": 1,\n      \"ttl\": 600\n    }\n  ],\n  \"authority\": [],\n  \"fullRcode\": 0,\n  \"header\": {\n    \"aa\": false,\n    \"ad\": false,\n    \"anCount\": 2,\n    \"arCount\": 1,\n    \"cd\": false,\n    \"nsCount\": 0,\n    \"opcode\": 0,\n    \"qdCount\": 1,\n    \"qr\": true,\n    \"ra\": true,\n    \"rcode\": 0,\n    \"rd\": true,\n    \"tc\": false\n  },\n  \"question\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"questionType\": \"A\",\n      \"questionTypeId\": 1\n    }\n  ],\n  \"rcodeName\": \"NOERROR\"\n}",
                false
            ),
            VRLFunctionExample(
                "Custom options",
                "res = dns_lookup!(\"dns.google\", options: {\"timeout\": 30, \"attempts\": 5})\nres.answers = map_values(res.answers) -> |value| {\n  value.ttl = 600\n  value\n}\n# remove extra responses for example\nres.answers = filter(res.answers) -> |_, value| {\n    value.rData == \"8.8.8.8\"\n}\n# remove class since this is also dynamic\nres.additional = map_values(res.additional) -> |value| {\n    del(value.class)\n    value\n}\nres",
                "{\n  \"additional\": [\n    {\n      \"domainName\": \"\",\n      \"rData\": \"OPT ...\",\n      \"recordType\": \"OPT\",\n      \"recordTypeId\": 41,\n      \"ttl\": 0\n    }\n  ],\n  \"answers\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"rData\": \"8.8.8.8\",\n      \"recordType\": \"A\",\n      \"recordTypeId\": 1,\n      \"ttl\": 600\n    }\n  ],\n  \"authority\": [],\n  \"fullRcode\": 0,\n  \"header\": {\n    \"aa\": false,\n    \"ad\": false,\n    \"anCount\": 2,\n    \"arCount\": 1,\n    \"cd\": false,\n    \"nsCount\": 0,\n    \"opcode\": 0,\n    \"qdCount\": 1,\n    \"qr\": true,\n    \"ra\": true,\n    \"rcode\": 0,\n    \"rd\": true,\n    \"tc\": false\n  },\n  \"question\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"questionType\": \"A\",\n      \"questionTypeId\": 1\n    }\n  ],\n  \"rcodeName\": \"NOERROR\"\n}",
                false
            ),
            VRLFunctionExample(
                "Custom server",
                "res = dns_lookup!(\"dns.google\", options: {\"servers\": [\"dns.quad9.net\"]})\nres.answers = map_values(res.answers) -> |value| {\n  value.ttl = 600\n  value\n}\n# remove extra responses for example\nres.answers = filter(res.answers) -> |_, value| {\n    value.rData == \"8.8.8.8\"\n}\n# remove class since this is also dynamic\nres.additional = map_values(res.additional) -> |value| {\n    del(value.class)\n    value\n}\nres",
                "{\n  \"additional\": [\n    {\n      \"domainName\": \"\",\n      \"rData\": \"OPT ...\",\n      \"recordType\": \"OPT\",\n      \"recordTypeId\": 41,\n      \"ttl\": 0\n    }\n  ],\n  \"answers\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"rData\": \"8.8.8.8\",\n      \"recordType\": \"A\",\n      \"recordTypeId\": 1,\n      \"ttl\": 600\n    }\n  ],\n  \"authority\": [],\n  \"fullRcode\": 0,\n  \"header\": {\n    \"aa\": false,\n    \"ad\": false,\n    \"anCount\": 2,\n    \"arCount\": 1,\n    \"cd\": false,\n    \"nsCount\": 0,\n    \"opcode\": 0,\n    \"qdCount\": 1,\n    \"qr\": true,\n    \"ra\": true,\n    \"rcode\": 0,\n    \"rd\": true,\n    \"tc\": false\n  },\n  \"question\": [\n    {\n      \"class\": \"IN\",\n      \"domainName\": \"dns.google\",\n      \"questionType\": \"A\",\n      \"questionTypeId\": 1\n    }\n  ],\n  \"rcodeName\": \"NOERROR\"\n}",
                false
            )
        )
    ),
    "get_env_var" to VRLFunction(
        name = "get_env_var",
        description = "Returns the value of the environment variable specified by <code>name</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "name",
                setOf("string"),
                "The name of the environment variable.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Get an environment variable",
                "get_env_var!(\"HOME\")",
                "/root",
                false
            )
        )
    ),
    "get_hostname" to VRLFunction(
        name = "get_hostname",
        description = "Returns the local system’s hostname.",
        isFallible = true,
        isPure = true,
        arguments = listOf(),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Get hostname",
                "get_hostname!()",
                "my-hostname",
                false
            )
        )
    ),
    "get_timezone_name" to VRLFunction(
        name = "get_timezone_name",
        description = "Returns the name of the timezone in the Vector configuration (see <a href=\"https://vector.dev/docs/reference/configuration/global-options/\">global configuration options</a>). If the configuration is set to <code>local</code>, then it attempts to determine the name of the timezone from the host OS. If this is not possible, then it returns the fixed offset of the local timezone for the current time in the format <code>\"[+-]HH:MM\"</code>, for example, <code>\"+02:00\"</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Get the IANA name of Vector’s timezone",
                "get_timezone_name!()",
                "UTC",
                false
            )
        )
    ),
    "http_request" to VRLFunction(
        name = "http_request",
        description = "Makes an HTTP request to the specified URL.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "url",
                setOf("string"),
                "The URL to make the HTTP request to.",
                true
            ),
            VRLFunctionArgument(
                "method",
                setOf("string"),
                "The HTTP method to use (e.g., GET, POST, PUT, DELETE). Defaults to GET.",
                false,
                defaultValue = "get"
            ),
            VRLFunctionArgument(
                "headers",
                setOf("object"),
                "An object containing HTTP headers to send with the request.",
                false,
                defaultValue = "{ }"
            ),
            VRLFunctionArgument(
                "body",
                setOf("string"),
                "The request body content to send.",
                false
            ),
            VRLFunctionArgument(
                "http_proxy",
                setOf("string"),
                "HTTP proxy URL to use for the request.",
                false
            ),
            VRLFunctionArgument(
                "https_proxy",
                setOf("string"),
                "HTTPS proxy URL to use for the request.",
                false
            ),
            VRLFunctionArgument(
                "redact_headers",
                setOf("boolean"),
                "Whether to redact sensitive header values in error messages.",
                false,
                defaultValue = true
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Basic HTTP request",
                ". = parse_json!(http_request!(\"https://httpbin.org/get\"))\n\n# Redact the origin ip\n.origin = redact!(.origin, filters: [r'.*'], redactor: {\"type\": \"text\", \"replacement\": \"***\"})\n# Delete any ids in headers\n.headers = filter(object!(.headers)) -> |key, _value| { !contains(key, \"id\", false) }\n.",
                "{\n  \"args\": {},\n  \"headers\": {\n    \"Accept\": \"*/*\",\n    \"Host\": \"httpbin.org\"\n  },\n  \"origin\": \"***\",\n  \"url\": \"https://httpbin.org/get\"\n}",
                false
            ),
            VRLFunctionExample(
                "HTTP request with bearer token",
                "parse_json!(http_request!(\"https://httpbin.org/bearer\", headers: {\"Authorization\": \"Bearer my_token\"}))",
                "{\n  \"authenticated\": true,\n  \"token\": \"my_token\"\n}",
                false
            ),
            VRLFunctionExample(
                "HTTP PUT request",
                ". = parse_json!(http_request!(\"https://httpbin.org/put\", method: \"put\"))\n\n# Redact the origin ip\n.origin = redact!(.origin, filters: [r'.*'], redactor: {\"type\": \"text\", \"replacement\": \"***\"})\n# Delete any ids in headers\n.headers = filter(object!(.headers)) -> |key, _value| { !contains(key, \"id\", false) }\n.",
                "{\n  \"args\": {},\n  \"data\": \"\",\n  \"files\": {},\n  \"form\": {},\n  \"headers\": {\n    \"Accept\": \"*/*\",\n    \"Content-Length\": \"0\",\n    \"Host\": \"httpbin.org\"\n  },\n  \"json\": null,\n  \"origin\": \"***\",\n  \"url\": \"https://httpbin.org/put\"\n}",
                false
            ),
            VRLFunctionExample(
                "HTTP POST request with body",
                ". = parse_json!(http_request!(\"https://httpbin.org/post\", method: \"post\", body: \"{\\\"data\\\":{\\\"hello\\\":\\\"world\\\"}}\"))\n\n# Redact the origin ip\n.origin = redact!(.origin, filters: [r'.*'], redactor: {\"type\": \"text\", \"replacement\": \"***\"})\n# Delete any ids in headers\n.headers = filter(object!(.headers)) -> |key, _value| { !contains(key, \"id\", false) }\n.",
                "{\n  \"args\": {},\n  \"data\": \"{\\\"data\\\":{\\\"hello\\\":\\\"world\\\"}}\",\n  \"files\": {},\n  \"form\": {},\n  \"headers\": {\n    \"Accept\": \"*/*\",\n    \"Content-Length\": \"26\",\n    \"Host\": \"httpbin.org\"\n  },\n  \"json\": {\n    \"data\": {\n      \"hello\": \"world\"\n    }\n  },\n  \"origin\": \"***\",\n  \"url\": \"https://httpbin.org/post\"\n}",
                false
            )
        )
    ),
    "reverse_dns" to VRLFunction(
        name = "reverse_dns",
        description = "Performs a reverse DNS lookup on the provided IP address to retrieve the associated hostname.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The IP address (IPv4 or IPv6) to perform the reverse DNS lookup on.",
                true
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Example",
                "reverse_dns!(\"127.0.0.1\")",
                "localhost",
                false
            )
        )
    )
)
