// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val timestampFunctions = mapOf(
    "format_timestamp" to VRLFunction(
        name = "format_timestamp",
        description = "Formats <code>value</code> into a string representation of the timestamp.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("timestamp"),
                "The timestamp to format as text.",
                true
            ),
            VRLFunctionArgument(
                "format",
                setOf("string"),
                "The format string as described by the <a href=\"https://docs.rs/chrono/latest/chrono/format/strftime/index.html#specifiers\">Chrono library</a>.",
                true
            ),
            VRLFunctionArgument(
                "timezone",
                setOf("string"),
                "The timezone to use when formatting the timestamp. The parameter uses the TZ identifier or <code>local</code>.",
                false
            )
        ),
        returnTypes = setOf("string"),
        examples = listOf(
            VRLFunctionExample(
                "Format a timestamp (ISO8601/RFC 3339)",
                "format_timestamp!(t'2020-10-21T16:00:00Z', format: \"%+\")",
                "2020-10-21T16:00:00+00:00",
                false
            ),
            VRLFunctionExample(
                "Format a timestamp (custom)",
                "format_timestamp!(t'2020-10-21T16:00:00Z', format: \"%v %R\")",
                "21-Oct-2020 16:00",
                false
            ),
            VRLFunctionExample(
                "Format a timestamp with custom format string",
                "format_timestamp!(t'2021-02-10T23:32:00+00:00', format: \"%d %B %Y %H:%M\")",
                "10 February 2021 23:32",
                false
            ),
            VRLFunctionExample(
                "Format a timestamp with timezone conversion",
                "format_timestamp!(t'2021-02-10T23:32:00+00:00', format: \"%d %B %Y %H:%M\", timezone: \"Europe/Berlin\")",
                "11 February 2021 00:32",
                false
            )
        )
    ),
    "now" to VRLFunction(
        name = "now",
        description = "Returns the current timestamp in the UTC timezone with nanosecond precision.",
        isFallible = false,
        isPure = true,
        arguments = listOf(),
        returnTypes = setOf("timestamp"),
        examples = listOf(
            VRLFunctionExample(
                "Generate a current timestamp",
                "now()",
                "2012-03-04T12:34:56.789012345Z",
                false
            )
        )
    )
)
