// Generated by scripts/refresh-vrl-functions.mjs from https://vector.dev/docs/reference/vrl/functions/ - do not hand-edit.
package eu.bcosp.vrlintellij.functions

val typeFunctions = mapOf(
    "array" to VRLFunction(
        name = "array",
        description = "Returns <code>value</code> if it is an array, otherwise returns an error. This enables the type checker to guarantee that the returned value is an array and can be used in any function that expects an array.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is an array.",
                true
            )
        ),
        returnTypes = setOf("array", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Declare an array type",
                "array!(.value)",
                "[1,2,3]",
                false
            ),
            VRLFunctionExample(
                "Valid array literal",
                "array([1,2,3])",
                "[1,2,3]",
                false
            ),
            VRLFunctionExample(
                "Invalid type",
                "array!(true)",
                "function call error for \"array\" at (0:12): expected array, got boolean",
                true
            )
        )
    ),
    "bool" to VRLFunction(
        name = "bool",
        description = "Returns <code>value</code> if it is a Boolean, otherwise returns an error. This enables the type checker to guarantee that the returned value is a Boolean and can be used in any function that expects a Boolean.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a Boolean.",
                true
            )
        ),
        returnTypes = setOf("boolean", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Valid Boolean",
                "bool(false)",
                "false",
                false
            ),
            VRLFunctionExample(
                "Invalid Boolean",
                "bool!(42)",
                "function call error for \"bool\" at (0:9): expected boolean, got integer",
                true
            ),
            VRLFunctionExample(
                "Valid Boolean from path",
                "bool!(.value)",
                "true",
                false
            )
        )
    ),
    "float" to VRLFunction(
        name = "float",
        description = "Returns <code>value</code> if it is a float, otherwise returns an error. This enables the type checker to guarantee that the returned value is a float and can be used in any function that expects a float.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a float.",
                true
            )
        ),
        returnTypes = setOf("float", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Declare a float type",
                ". = { \"value\": 42.0 }\nfloat(.value)",
                "42",
                false
            ),
            VRLFunctionExample(
                "Declare a float type (literal)",
                "float(3.1415)",
                "3.1415",
                false
            ),
            VRLFunctionExample(
                "Invalid float type",
                "float!(true)",
                "function call error for \"float\" at (0:12): expected float, got boolean",
                true
            )
        )
    ),
    "int" to VRLFunction(
        name = "int",
        description = "Returns <code>value</code> if it is an integer, otherwise returns an error. This enables the type checker to guarantee that the returned value is an integer and can be used in any function that expects an integer.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is an integer.",
                true
            )
        ),
        returnTypes = setOf("integer", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Declare an integer type",
                ". = { \"value\": 42 }\nint(.value)",
                "42",
                false
            ),
            VRLFunctionExample(
                "Declare an integer type (literal)",
                "int(42)",
                "42",
                false
            ),
            VRLFunctionExample(
                "Invalid integer type",
                "int!(true)",
                "function call error for \"int\" at (0:10): expected integer, got boolean",
                true
            )
        )
    ),
    "is_array" to VRLFunction(
        name = "is_array",
        description = "Check if the <code>value</code>’s type is an array.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is an array.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid array",
                "is_array([1, 2, 3])",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_array(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Boolean",
                "is_array(true)",
                "false",
                false
            ),
            VRLFunctionExample(
                "Null",
                "is_array(null)",
                "false",
                false
            )
        )
    ),
    "is_boolean" to VRLFunction(
        name = "is_boolean",
        description = "Check if the <code>value</code>’s type is a boolean.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a Boolean.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid boolean",
                "is_boolean(false)",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_boolean(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Null",
                "is_boolean(null)",
                "false",
                false
            )
        )
    ),
    "is_empty" to VRLFunction(
        name = "is_empty",
        description = "Check if the object, array, or string has a length of <code>0</code>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string", "object", "array"),
                "The value to check.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Empty array",
                "is_empty([])",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-empty string",
                "is_empty(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Non-empty object",
                "is_empty({\"foo\": \"bar\"})",
                "false",
                false
            ),
            VRLFunctionExample(
                "Empty string",
                "is_empty(\"\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Empty object",
                "is_empty({})",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-empty array",
                "is_empty([1,2,3])",
                "false",
                false
            )
        )
    ),
    "is_float" to VRLFunction(
        name = "is_float",
        description = "Check if the <code>value</code>’s type is a float.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a float.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid float",
                "is_float(0.577)",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_float(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Boolean",
                "is_float(true)",
                "false",
                false
            ),
            VRLFunctionExample(
                "Null",
                "is_float(null)",
                "false",
                false
            )
        )
    ),
    "is_integer" to VRLFunction(
        name = "is_integer",
        description = "Check if the <code>value</code>’s type is an integer.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is an integer.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid integer",
                "is_integer(1)",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_integer(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Null",
                "is_integer(null)",
                "false",
                false
            )
        )
    ),
    "is_json" to VRLFunction(
        name = "is_json",
        description = "Check if the string is a valid JSON document.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The value to check if it is a valid JSON document.",
                true
            ),
            VRLFunctionArgument(
                "variant",
                setOf("string"),
                "The variant of the JSON type to explicitly check for.",
                false,
                enumValues = listOf("object", "array", "string", "number", "bool", "null")
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid JSON object",
                "is_json(\"{}\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-valid value",
                "is_json(\"{\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Exact variant",
                "is_json(\"{}\", variant: \"object\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-valid exact variant",
                "is_json(\"{}\", variant: \"array\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Valid JSON string",
                "is_json(s'\"test\"')",
                "true",
                false
            )
        )
    ),
    "is_null" to VRLFunction(
        name = "is_null",
        description = "Check if <code>value</code>’s type is <code>null</code>. For a more relaxed function, see <a href=\"https://vector.dev/docs/reference/vrl/functions/#is_nullish\"><code>is_nullish</code></a>.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is <code>null</code>.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Null value",
                "is_null(null)",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_null(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Array",
                "is_null([1, 2, 3])",
                "false",
                false
            )
        )
    ),
    "is_nullish" to VRLFunction(
        name = "is_nullish",
        description = "Determines whether <code>value</code> is nullish. Returns <code>true</code> if the specified <code>value</code> is <code>null</code>, an empty string, a string containing only whitespace, or the string <code>\"-\"</code>. Returns <code>false</code> otherwise.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check for nullishness, for example, a useless value.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Null detection (blank string)",
                "is_nullish(\"\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Null detection (dash string)",
                "is_nullish(\"-\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Null detection (whitespace)",
                "is_nullish(\"\n  \n\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Null",
                "is_nullish(null)",
                "true",
                false
            )
        )
    ),
    "is_object" to VRLFunction(
        name = "is_object",
        description = "Check if <code>value</code>’s type is an object.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is an object.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid object",
                "is_object({\"foo\": \"bar\"})",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_object(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Boolean",
                "is_object(true)",
                "false",
                false
            )
        )
    ),
    "is_regex" to VRLFunction(
        name = "is_regex",
        description = "Check if <code>value</code>’s type is a regex.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a regex.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid regex",
                "is_regex(r'pattern')",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_regex(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Null value",
                "is_regex(null)",
                "false",
                false
            )
        )
    ),
    "is_string" to VRLFunction(
        name = "is_string",
        description = "Check if <code>value</code>’s type is a string.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a string.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid string",
                "is_string(\"a string\")",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_string([1, 2, 3])",
                "false",
                false
            ),
            VRLFunctionExample(
                "Boolean",
                "is_string(true)",
                "false",
                false
            ),
            VRLFunctionExample(
                "Null",
                "is_string(null)",
                "false",
                false
            )
        )
    ),
    "is_timestamp" to VRLFunction(
        name = "is_timestamp",
        description = "Check if <code>value</code>’s type is a timestamp.",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a timestamp.",
                true
            )
        ),
        returnTypes = setOf("boolean"),
        examples = listOf(
            VRLFunctionExample(
                "Valid timestamp",
                "is_timestamp(t'2021-03-26T16:00:00Z')",
                "true",
                false
            ),
            VRLFunctionExample(
                "Non-matching type",
                "is_timestamp(\"a string\")",
                "false",
                false
            ),
            VRLFunctionExample(
                "Boolean value",
                "is_timestamp(true)",
                "false",
                false
            )
        )
    ),
    "object" to VRLFunction(
        name = "object",
        description = "Returns <code>value</code> if it is an object, otherwise returns an error. This enables the type checker to guarantee that the returned value is an object and can be used in any function that expects an object.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is an object.",
                true
            )
        ),
        returnTypes = setOf("object", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Declare an object type",
                ". = { \"value\": { \"field1\": \"value1\", \"field2\": \"value2\" } }\nobject(.value)",
                "{\n  \"field1\": \"value1\",\n  \"field2\": \"value2\"\n}",
                false
            ),
            VRLFunctionExample(
                "Invalid type",
                "object!(true)",
                "function call error for \"object\" at (0:13): expected object, got boolean",
                true
            )
        )
    ),
    "string" to VRLFunction(
        name = "string",
        description = "Returns <code>value</code> if it is a string, otherwise returns an error. This enables the type checker to guarantee that the returned value is a string and can be used in any function that expects a string.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a string.",
                true
            )
        ),
        returnTypes = setOf("string", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Declare a string type",
                ". = { \"message\": \"{\\\"field\\\": \\\"value\\\"}\" }\nstring(.message)",
                "{\"field\": \"value\"}",
                false
            ),
            VRLFunctionExample(
                "Invalid type",
                "string!(true)",
                "function call error for \"string\" at (0:13): expected string, got boolean",
                true
            )
        )
    ),
    "tag_types_externally" to VRLFunction(
        name = "tag_types_externally",
        description = "<p>Adds type information to all (nested) scalar values in the provided <code>value</code>.</p>\n\n<p>The type information is added externally, meaning that <code>value</code> has the form of <code>\"type\": value</code> after this transformation.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to tag with types.",
                true
            )
        ),
        returnTypes = setOf("object", "array", "null"),
        examples = listOf(
            VRLFunctionExample(
                "Tag types externally (scalar)",
                "tag_types_externally(123)",
                "{\n  \"integer\": 123\n}",
                false
            ),
            VRLFunctionExample(
                "Tag types externally (object)",
                "tag_types_externally({\n    \"message\": \"Hello world\",\n    \"request\": {\n        \"duration_ms\": 67.9\n    }\n})",
                "{\n  \"message\": {\n    \"string\": \"Hello world\"\n  },\n  \"request\": {\n    \"duration_ms\": {\n      \"float\": 67.9\n    }\n  }\n}",
                false
            ),
            VRLFunctionExample(
                "Tag types externally (array)",
                "tag_types_externally([\"foo\", \"bar\"])",
                "[{\"string\":\"foo\"},{\"string\":\"bar\"}]",
                false
            ),
            VRLFunctionExample(
                "Tag types externally (null)",
                "tag_types_externally(null)",
                "",
                false
            )
        )
    ),
    "timestamp" to VRLFunction(
        name = "timestamp",
        description = "Returns <code>value</code> if it is a timestamp, otherwise returns an error. This enables the type checker to guarantee that the returned value is a timestamp and can be used in any function that expects a timestamp.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The value to check if it is a timestamp.",
                true
            )
        ),
        returnTypes = setOf("timestamp", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Declare a timestamp type",
                "timestamp(t'2020-10-10T16:00:00Z')",
                "t'2020-10-10T16:00:00Z'",
                false
            ),
            VRLFunctionExample(
                "Invalid type",
                "timestamp!(true)",
                "function call error for \"timestamp\" at (0:16): expected timestamp, got boolean",
                true
            )
        )
    ),
    "type_def" to VRLFunction(
        name = "type_def",
        description = "<p>Returns the type definition of an expression at runtime.</p>\n\n<p>This is a debug function that is <em>UNSTABLE</em>. Behavior is <em>NOT</em> guaranteed even though it is technically usable.</p>",
        isFallible = false,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("any"),
                "The expression to get the type definition for.",
                true
            )
        ),
        returnTypes = setOf("any"),
        examples = listOf(
            VRLFunctionExample(
                "return type definition",
                "type_def(42)",
                "{\n  \"integer\": true\n}",
                false
            )
        )
    ),
    "validate_json_schema" to VRLFunction(
        name = "validate_json_schema",
        description = "Check if <code>value</code> conforms to a JSON Schema definition. This function validates a JSON payload against a JSON Schema definition. It can be used to ensure that the data structure and types in <code>value</code> match the expectations defined in <code>schema_definition</code>.",
        isFallible = true,
        isPure = true,
        arguments = listOf(
            VRLFunctionArgument(
                "value",
                setOf("string"),
                "The value to check if it conforms to the JSON schema definition.",
                true
            ),
            VRLFunctionArgument(
                "schema_definition",
                setOf("string"),
                "The location (path) of the JSON Schema definition.",
                true
            ),
            VRLFunctionArgument(
                "ignore_unknown_formats",
                setOf("boolean"),
                "Unknown formats can be silently ignored by setting this to <code>true</code> and validation continues without failing due to those fields.",
                false
            )
        ),
        returnTypes = setOf("boolean", "error"),
        examples = listOf(
            VRLFunctionExample(
                "Payload contains a valid email",
                "validate_json_schema!(s'{ \"productUser\": \"valid@email.com\" }', \"tests/data/jsonschema/validate_json_schema/schema_with_email_format.json\", false)",
                "true",
                false
            ),
            VRLFunctionExample(
                "Payload contains an invalid email",
                "validate_json_schema!(s'{ \"productUser\": \"invalidEmail\" }', \"tests/data/jsonschema/validate_json_schema/schema_with_email_format.json\", false)",
                "function call error for \"validate_json_schema\" at (0:142): JSON schema validation failed: \"invalidEmail\" is not a \"email\" at /productUser",
                true
            ),
            VRLFunctionExample(
                "Payload contains a custom format declaration",
                "validate_json_schema!(s'{ \"productUser\": \"a-custom-formatted-string\" }', \"tests/data/jsonschema/validate_json_schema/schema_with_custom_format.json\", false)",
                "function call error for \"validate_json_schema\" at (0:156): Failed to compile schema: Unknown format: 'my-custom-format'. Adjust configuration to ignore unrecognized formats",
                true
            ),
            VRLFunctionExample(
                "Payload contains a custom format declaration, with ignore_unknown_formats set to true",
                "validate_json_schema!(s'{ \"productUser\": \"a-custom-formatted-string\" }', \"tests/data/jsonschema/validate_json_schema/schema_with_custom_format.json\", true)",
                "true",
                false
            )
        )
    )
)
